// templates/admin-template-react/src/Components/Core/Subheader/Subheader.js
function Subheader() {

    return (
        <>
            <div className="subheader d-md-flex align-items-center justify-content-between px-3 px-sm-5">
                <div
                    className="d-flex flex-column flex-sm-row align-items-baseline align-items-sm-center flex-wrap h-100 py-3">
                    <h6 className="text-dark font-weight-bold mt-1 mb-0 mb-sm-1 mr-5" id="breadcrumb-title">Profile 1
                    </h6>
                    <ul className="breadcrumb p-0" id="breadcrumb-list">
                        <li className="breadcrumb-item">
                            <a href="#" onClick={(e) => e.preventDefault()} className="text-muted">Dashboard</a>
                        </li>
                        <li className="breadcrumb-item">
                            <a href="#" onClick={(e) => e.preventDefault()} className="text-muted">Default</a>
                        </li>
                    </ul>
                </div>
                <div className="d-flex align-items-center flex-wrap py-3">
                    <div
                        className="dropdown"
                        data-bs-toggle="tooltip"
                        data-bs-placement="top"
                        data-bs-title="Quick actions"
                    >
                        <button type="button"
                            className="btn btn-icon dropdown-toggle btn-outline-primary btn-sm font-weight-bold px-5 mr-3 my-1"
                            data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i className="material-icons">person_add</i> Add Member
                        </button>
                        <div className="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a className="dropdown-item" href="#">Action</a>
                            <a className="dropdown-item" href="#">Another action</a>
                            <a className="dropdown-item" href="#">Something else here</a>
                        </div>
                    </div>

                    <div
                        className="dropdown"
                        data-bs-toggle="tooltip"
                        data-bs-placement="top"
                        data-bs-title="Quick actions"
                    >
                        <button type="button"
                            className="btn btn-icon dropdown-toggle btn-outline-primary btn-sm font-weight-bold px-5 my-1"
                            data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i className="material-icons">article</i> New Report
                        </button>
                        <div className="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a className="dropdown-item" href="#">Action</a>
                            <a className="dropdown-item" href="#">Another action</a>
                            <a className="dropdown-item" href="#">Something else here</a>
                        </div>
                    </div>
                </div>


            </div>
        </>
    )
}

export default Subheader

// templates/admin-template-angular/src/app/core/sub-header/sub-header.component.ts
import { AfterViewInit, Component, Input, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'sm-sub-header',
  templateUrl: './sub-header.component.html',
  styleUrls: ['./sub-header.component.scss'],
  encapsulation: ViewEncapsulation.None
})
export class SubHeaderComponent implements AfterViewInit {

  @Input('isSidebarExpanded') isSidebarExpanded!: boolean;
  
  ngAfterViewInit(): void {

    window.addEventListener('click', (e) => {

      document.querySelectorAll('.dropdown-menu-show')
        .forEach(menu => {
          menu.classList.remove('dropdown-menu-show')
        });

      document.querySelectorAll('.dropdown-button-active')
        .forEach(menu => {
          menu.classList.remove('dropdown-button-active')
        });

    });

  }

  toggleMenu($event: Event, property: string) {

    $event.stopPropagation();

    const menu = document.querySelector(`.${property}`);
    const toggleButton = document.querySelector(`.${property}Button`);

    const isExpanded = menu?.classList.contains('dropdown-menu-show');

    document.querySelectorAll('.dropdown-menu')
      .forEach(menu => menu.classList.remove('dropdown-menu-show'));

    document.querySelectorAll('.dropdown-button')
      .forEach(menu => menu.classList.remove('dropdown-button-active'));

    if (!isExpanded) {
      menu?.classList.toggle('dropdown-menu-show');
      toggleButton?.classList.toggle('dropdown-button-active');
    }
  }
}

<div class="subheader" [class.subheader-sidebar-not-expanded]="!isSidebarExpanded">
    <div class="subheader-breadcrumbs-wrapper">
        <h6 class="" id="breadcrumb-title">Dashboard</h6>
        <ul class="breadcrumb" id="breadcrumb-list">
            <li class="breadcrumb-item">
                <a class="text-muted">Dashboard</a>
            </li>
        </ul>
    </div>

    <div class="subheader-dropdowns-wrapper">
        <div class="dropdown" data-bs-toggle="tooltip" data-bs-placement="top" title="Quick actions"
            data-bs-custom-class="sub-header-custom-tooltip">
            <button (click)="toggleMenu($event, 'memberMenu')" id="memberButton" type="button"
                class="dropdown-button memberMenuButton" aria-haspopup="true" aria-expanded="false">
                <i class="material-icons">person_add</i> Add Member
            </button>
            <div class="dropdown-menu memberMenu" aria-labelledby="dropdownMenuButton"
                (click)="toggleMenu($event, 'memberMenu')">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </div>
        <div class="dropdown" data-bs-toggle="tooltip" data-bs-placement="top" title="Quick actions"
            data-bs-custom-class="sub-header-custom-tooltip">
            <button (click)="toggleMenu($event, 'reportMenu')" id="reportButton" type="button"
                class="dropdown-button reportMenuButton" aria-haspopup="true" aria-expanded="false">
                <i class="material-icons">article</i> New Report
            </button>
            <div class="dropdown-menu reportMenu" aria-labelledby="dropdownMenuButton"
                (click)="toggleMenu($event, 'reportMenu')">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </div>
    </div>
</div>
