// templates/admin-template-angular/src/app/pages/notifications/notifications/notifications.component.ts
import { AfterViewInit, Component, ViewChild } from '@angular/core';
import { InputComponent } from 'smart-webcomponents-angular/input';
import { ToastComponent } from 'smart-webcomponents-angular/toast';

@Component({
  selector: 'sm-notifications',
  templateUrl: './notifications.component.html',
  styleUrls: ['./notifications.component.scss']
})
export class NotificationsComponent implements AfterViewInit {

  @ViewChild('toast', { read: ToastComponent, static: false }) toast!: ToastComponent;
  @ViewChild('messageInput', { read: InputComponent, static: false }) messageInput!: InputComponent;

  constructor() { }

  ngAfterViewInit(): void {

  }

  messageInputChange() {

    this.toast.value = this.messageInput.value;

  }

  typeInputChange($event: CustomEvent) {

    this.toast.type = $event.detail.value;

  }

  enableAutoCloseChange($event: CustomEvent) {

    this.toast.autoClose = $event.detail.value;

  }

  enableBlinkChange($event: CustomEvent) {

    const toast = document.querySelector('#toast');
    toast!.classList.toggle('blink', $event.detail.value);

  }

  enableCloseButtonChange($event: CustomEvent) {

    this.toast.showCloseButton = $event.detail.value;

  }

  topLeftChange() {

    this.toast.position = 'top-left';

  }

  topRightChange() {

    this.toast.position = 'top-right';

  }

  bottomLeftChange() {

    this.toast.position = 'bottom-left';

  }

  bottomRightChange() {

    this.toast.position = 'bottom-right';

  }

  showToast() {

    this.toast.open();

  }

  clearAllToasts() {

    this.toast.closeAll();

  }
}

<div class="container notifications">
    <div class="custom-row">
        <div class="notifications-header custom-col">
            <h4>Notifications</h4>
        </div>
    </div>

    <div class="custom-card">
        <div class="card-body">
            <p>Smart.Toast represents an element which displays an unobtrusive notification to the user.</p>
            <br />
            <div class="custom-row">
                <div class="notifications-entity-lg-6 custom-col">
                    <div>
                        <label>Message</label>
                        <smart-input #messageInput (onChange)="messageInputChange()" id="messageInput"
                            placeholder="Enter a message" value="Sample notification">
                        </smart-input>
                        <label>Type</label>
                        <smart-input (onChange)="typeInputChange($event)" id="typeInput" drop-down-height="400"
                            data-source='["info", "warning", "success", "error", "mail", "time"]'
                            drop-down-button-position="right" [readonly]="true" value="warning"></smart-input>
                        <smart-check-box (onChange)="enableAutoCloseChange($event)" id="enableAutoClose" [checked]="true">Auto close</smart-check-box>
                        <smart-check-box (onChange)="enableBlinkChange($event)" id="enableBlink" [checked]="true">Blink</smart-check-box>
                        <smart-check-box (onChange)="enableCloseButtonChange($event)" id="enableCloseButton" [checked]="true">Close button</smart-check-box>
                    </div>
                </div>

                <div class="notifications-entity-lg-6 custom-col">
                    <div>
                        <label>Position</label>
                        <smart-radio-button (onChange)="topLeftChange()" id="topLeft">Top-left</smart-radio-button>
                        <smart-radio-button (onChange)="topRightChange()" id="topRight">Top-right</smart-radio-button>
                        <smart-radio-button (onChange)="bottomLeftChange()" id="bottomLeft">Bottom-left</smart-radio-button>
                        <smart-radio-button (onChange)="bottomRightChange()" id="bottomRight" [checked]="true">Bottom-right</smart-radio-button>
                    </div>
                </div>
            </div>

            <div class="notifications-buttons-wrapper">
                <smart-button (click)="showToast()" id="show" class="small-button primary">Show notification</smart-button>&nbsp;<smart-button
                    (click)="clearAllToasts()" id="clearAll" class="small-button primary outlined">Clear all</smart-button>
            </div>
        </div>
    </div>
</div>

<smart-toast #toast id="toast" class="blink" auto-close position="bottom-right" show-close-button type="warning">Sample
    notification</smart-toast>

// templates/admin-template-react/src/Pages/Notification/Notifications.js
import './Notifications.scss';
import { useEffect, useRef } from 'react';

import withAnimation from '../../hoc/withAnimation';

import { Toast, Button, CheckBox, RadioButton, Input } from '../../smartImports';

import { defaultTitle } from '../../contexts/themeContext';

function Notifications() {

    const toastRef = useRef(null);

    useEffect(() => { document.title = `Notifications - ${defaultTitle}` }, []);

    return (
        <>
            <div className="container notifications-page">
                <div className="row">
                    <div className="col-12 mb-3"><h4>Notifications</h4></div>
                </div>

                <div className="card">
                    <div className="card-body">
                        <p>Smart.Toast represents an element which displays an unobtrusive notification to the user.</p>
                        <br />
                        <div className="row">
                            <div className="col-lg-6">
                                <div className="d-flex flex-column">
                                    <label>Message</label>
                                    <Input
                                        onChange={(e) => toastRef.current.value = e.target.value}
                                        id="messageInput"
                                        placeholder="Enter a message"
                                        value="Sample notification"
                                    ></Input>
                                    <label>Type</label>
                                    <Input
                                        onChange={(e) => toastRef.current.type = e.detail.value}
                                        id="typeInput"
                                        dropDownHeight="400"
                                        dataSource={["info", "warning", "success", "error", "mail", "time"]}
                                        dropDownButtonPosition="right"
                                        readonly
                                        value="warning"
                                    ></Input>
                                    <CheckBox
                                        id="enableAutoClose"
                                        checked
                                        onChange={(e) => toastRef.current.autoClose = e.detail.value}
                                    >Auto close</CheckBox>
                                    <CheckBox
                                        id="enableBlink"
                                        checked
                                        onChange={(e) => toastRef.current.classList.toggle('blink', e.detail.value)}
                                    >Blink</CheckBox>
                                    <CheckBox
                                        id="enableCloseButton"
                                        checked
                                        onChange={(e) => toastRef.current.showCloseButton = e.detail.value}
                                    >Close button</CheckBox>
                                </div>
                            </div>

                            <div className="col-lg-6">
                                <div className="d-flex flex-column">
                                    <label>Position</label>
                                    <RadioButton
                                        id="topLeft"
                                        onChange={(e) => toastRef.current.position = 'top-left'}
                                    >Top-left</RadioButton>
                                    <RadioButton
                                        id="topRight"
                                        onChange={(e) => toastRef.current.position = 'top-right'}
                                    >Top-right</RadioButton>
                                    <RadioButton
                                        id="bottomLeft"
                                        onChange={(e) => toastRef.current.position = 'bottom-left'}
                                    >Bottom-left</RadioButton>
                                    <RadioButton
                                        id="bottomRight"
                                        onChange={(e) => toastRef.current.position = 'bottom-right'}
                                        checked
                                    >Bottom-right</RadioButton>
                                </div>
                            </div>
                        </div>

                        <div className="mt-5">
                            <Button
                                onClick={() => toastRef.current.open()}
                                id="show"
                                className="small-button primary"
                            >Show notification</Button>&nbsp;<Button
                                onClick={() => toastRef.current.closeAll()}
                                id="clearAll"
                                className="small-button primary outlined"
                            >Clear all</Button>
                        </div>
                    </div>
                </div>
            </div>
            <Toast
                ref={toastRef}
                id="toast"
                className="blink"
                autoClose
                position="bottom-right"
                showCloseButton
                type="warning"
            >Sample notification</Toast>
        </>
    )
}

export default withAnimation(Notifications)
