// templates/admin-template-angular/src/app/pages/ui-elements/cards/cards.component.ts
import { Component, OnInit, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'sm-cards',
  templateUrl: './cards.component.html',
  styleUrls: ['./cards.component.scss'],
  encapsulation: ViewEncapsulation.None
})
export class CardsComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div id="cardsView" class="container cards">
    <div class="custom-row">
        <div class="cards-header custom-col"><h4>Cards</h4></div>
    </div>

    <div class="cards-with-images-wrapper custom-row">
        <div class="cars-card-image-link-button custom-col">
            <smart-card>
                <div class="custom-card h-100">
                    <div class="card-body">
                        <div class="img-as-background">
                            <img src="../../../../assets/images/travel/16.jpg"/>
                        </div>
                        <h4 class='cards-card-header'>Card with image and links</h4>
                        <p class='cards-card-content'>Nulla tempus neque id eros blandit, id congue sem ultricies. Nulla molestie viverra aliquet.
                            Praesent feugiat mollis lacus, quis sagittis leo.</p>
                        <a href="#">Sample link 1</a>&nbsp;<a href="#">Sample link 2</a>
                    </div>
                </div>
            </smart-card>
        </div>

        <div class="cars-card-image-link-button custom-col">
            <smart-card>
                <div class="custom-card h-100">
                    <div class="card-body">
                        <div class="img-as-background">
                            <img src="../../../../assets/images/travel/4.jpg"/>
                        </div>
                        <h4 class='cards-card-header'>Card with image and button</h4>
                        <p class='cards-card-content'>Pellentesque eget magna augue. Nam accumsan dignissim vulputate. In hac habitasse platea
                            dictumst.</p>
                        <smart-button class="primary">Sample button</smart-button>
                    </div>
                </div>
            </smart-card>
        </div>

        <div class="cars-card-image-link-button custom-col">
            <smart-card>
                <div class="custom-card h-100">
                    <div class="card-body">
                        <div class="img-as-background">
                            <img src="../../../../assets/images/travel/25.jpg"/>
                        </div>
                        <h4 class='cards-card-header'>Card with image and list</h4>
                        <p class='cards-card-content'>Aliquam erat volutpat. Aenean tincidunt scelerisque mauris, in pharetra mi venenatis ut.</p>
                        <ul class="list">
                            <li>Praesent scelerisque</li>
                            <li>Vestibulum quis</li>
                            <li>Mauris odio</li>
                            <li>Integer</li>
                        </ul>
                    </div>
                </div>
            </smart-card>
        </div>
    </div>

    <div class="cards-with-links-buttons-wrapper custom-row">
        <div class="cars-card-image-link-button custom-col">
            <smart-card>
                <div class="custom-card h-100">
                    <div class="card-body">
                        <h4 class='cards-card-header'>Card with links</h4>
                        <p class='cards-card-content'>Nulla tempus neque id eros blandit, id congue sem ultricies. Nulla molestie viverra aliquet. Praesent feugiat mollis lacus, quis sagittis leo.</p>
                        <a href="#">Sample link 1</a>&nbsp;<a href="#">Sample link 2</a>
                    </div>
                </div>
            </smart-card>
        </div>

        <div class="cars-card-image-link-button custom-col">
            <smart-card>
                <div class="custom-card h-100">
                    <div class="card-body">
                        <div class="content-holder-wrapper">
                            <div class="content-holder">
                                <h4 class='cards-card-header'>Card with button <span class="font-size-16px"> position bottom</span></h4>
                                <p class='cards-card-content'>Pellentesque eget magna augue. Nam accumsan dignissim vulputate. In hac habitasse platea dictumst.</p>
                            </div>

                            <div class="cards-card-with-button-button-wrapper">
                                <smart-button class="primary">Sample button</smart-button>
                            </div>
                        </div>
                    </div>
                </div>
            </smart-card>
        </div>

        <div class="cars-card-image-link-button custom-col">
            <smart-card>
                <div class="custom-card h-100">
                    <div class="card-body">
                        <h4 class='cards-card-header'>Card with list</h4>
                        <p class='cards-card-content'>Aliquam erat volutpat. Aenean tincidunt scelerisque mauris, in pharetra mi venenatis ut.</p>
                        <ul class="list">
                            <li>Praesent scelerisque</li>
                            <li>Vestibulum quis</li>
                            <li>Mauris odio</li>
                            <li>Integer</li>
                        </ul>
                    </div>
                </div>
            </smart-card>
        </div>
    </div>

    <div class="cards-with-tabs-wrapper custom-row">
        <div class="card-with-tab custom-col">
            <smart-card>
                <div class="custom-card h-100">
                    <div class="card-body">
                        <smart-tabs class="m-0 w-100">
                            <smart-tab-item label="Tab 1">
                                <h4 class='cards-card-header'>Card with tabs</h4>
                                <p class='cards-card-content'>Nulla tempus neque id eros blandit, id congue sem ultricies. Nulla molestie viverra aliquet. Praesent feugiat mollis lacus, quis sagittis leo.</p>
                                <smart-button class="primary">Sample button</smart-button>
                            </smart-tab-item>

                            <smart-tab-item label="Tab 2">
                                <h4 class='cards-card-header'>Card with tabs</h4>
                                <p class='cards-card-content'>Nunc lacus mi, fringilla et dignissim eu, pharetra sit amet sapien. Praesent lectus tellus, iaculis ut commodo id, auctor quis velit.</p>
                                <smart-button class="primary">Sample button 2</smart-button>
                            </smart-tab-item>

                            <smart-tab-item label="Tab 3">
                                <h4 class='cards-card-header'>Card with tabs</h4>
                                <p class='cards-card-content'>Aenean et viverra nibh. Sed aliquam facilisis libero, quis lacinia metus gravida ac. Curabitur vitae turpis accumsan diam malesuada placerat quis in felis.</p>
                                <smart-button class="primary">Sample button 3</smart-button>
                            </smart-tab-item>
                        </smart-tabs>
                    </div>
                </div>
            </smart-card>
        </div>

        <div class="card-with-tab custom-col">
            <smart-card>
                <div class="custom-card h-100">
                    <div class="card-body">
                        <smart-tabs class="m-0 w-100">
                            <smart-tab-item label="Pill 1">
                                <h4 class='cards-card-header'>Card with pills</h4>
                                <p class='cards-card-content'>Nulla tempus neque id eros blandit, id congue sem ultricies. Nulla molestie viverra aliquet. Praesent feugiat mollis lacus, quis sagittis leo.</p>
                                <smart-button class="primary">Sample button</smart-button>
                            </smart-tab-item>

                            <smart-tab-item label="Pill 2">
                                <h4 class='cards-card-header'>Card with pills</h4>
                                <p class='cards-card-content'>Nunc lacus mi, fringilla et dignissim eu, pharetra sit amet sapien. Praesent lectus tellus, iaculis ut commodo id, auctor quis velit.</p>
                                <smart-button class="primary">Sample button 2</smart-button>
                            </smart-tab-item>

                            <smart-tab-item label="Pill 3">
                                <h4 class='cards-card-header'>Card with pills</h4>
                                <p class='cards-card-content'>Aenean et viverra nibh. Sed aliquam facilisis libero, quis lacinia metus gravida ac. Curabitur vitae turpis accumsan diam malesuada placerat quis in felis.</p>
                                <smart-button class="primary">Sample button 3</smart-button>
                            </smart-tab-item>
                        </smart-tabs>
                    </div>
                </div>
            </smart-card>

        </div>
    </div>
</div>

// templates/admin-template-react/src/Pages/UIElements/Cards/Cards.js
import './Cards.scss';
import { useEffect } from 'react';

import withAnimation from '../../../hoc/withAnimation';
import { Card, Button, Tabs, TabItem } from '../../../smartImports';

import { defaultTitle } from '../../../contexts/themeContext';

function Cards() {

    useEffect(() => { document.title = `Cards - ${defaultTitle}` }, []);

    return (
        <div id="cardsView" className="container cards-page">
            <div className="row">
                <div className="col-12 mb-3"><h4>Cards</h4></div>
            </div>

            <div className="row">
                <div className="col-lg-4 mb-5">
                    <Card className="h-100">
                        <div className="card h-100 shadow-3 hover-shadow-6">
                            <div className="card-body">
                                <div className="img-as-background h-200 mb-3">
                                    <img alt="" src="assets/images/travel/16.jpg" />
                                </div>
                                <h4>Card with image and links</h4>
                                <p>Nulla tempus neque id eros blandit, id congue sem ultricies. Nulla molestie viverra aliquet.
                                    Praesent feugiat mollis lacus, quis sagittis leo.</p>
                                <a href="#">Sample link 1</a>&nbsp;<a href="#">Sample link 2</a>
                            </div>
                        </div>
                    </Card>
                </div>

                <div className="col-lg-4 mb-5">
                    <Card className="h-100">
                        <div className="card h-100 shadow-3 hover-shadow-6">
                            <div className="card-body">
                                <div className="img-as-background h-200 mb-3">
                                    <img alt="" src="assets/images/travel/4.jpg" />
                                </div>
                                <h4>Card with image and button</h4>
                                <p>Pellentesque eget magna augue. Nam accumsan dignissim vulputate. In hac habitasse platea
                                    dictumst.</p>
                                <Button className="primary">Sample button</Button>
                            </div>
                        </div>
                    </Card>
                </div>

                <div className="col-lg-4 mb-5">
                    <Card className="h-100">
                        <div className="card h-100 shadow-3 hover-shadow-6">
                            <div className="card-body">
                                <div className="img-as-background h-200 mb-3">
                                    <img alt="" src="assets/images/travel/25.jpg" />
                                </div>
                                <h4>Card with image and list</h4>
                                <p>Aliquam erat volutpat. Aenean tincidunt scelerisque mauris, in pharetra mi venenatis ut.</p>
                                <ul className="list">
                                    <li>Praesent scelerisque</li>
                                    <li>Vestibulum quis</li>
                                    <li>Mauris odio</li>
                                    <li>Integer</li>
                                </ul>
                            </div>
                        </div>
                    </Card>
                </div>
            </div>

            <div className="row">
                <div className="col-lg-4 mb-5">
                    <Card className="h-100">
                        <div className="card h-100 shadow-3 hover-shadow-6">
                            <div className="card-body">
                                <h4>Card with links</h4>
                                <p>Nulla tempus neque id eros blandit, id congue sem ultricies. Nulla molestie viverra aliquet. Praesent feugiat mollis lacus, quis sagittis leo.</p>
                                <a href="#">Sample link 1</a>&nbsp;<a href="#">Sample link 2</a>
                            </div>
                        </div>
                    </Card>
                </div>

                <div className="col-lg-4 mb-5">
                    <Card className="h-100">
                        <div className="card h-100 shadow-3 hover-shadow-6">
                            <div className="card-body">
                                <div className="h-100 d-flex flex-column">
                                    <div className="content-holder">
                                        <h4>Card with button <span className="font-size-16px"> position bottom</span></h4>
                                        <p>Pellentesque eget magna augue. Nam accumsan dignissim vulputate. In hac habitasse platea dictumst.</p>
                                    </div>

                                    <div className="w-100 mt-auto">
                                        <Button className="primary w-100">Sample button</Button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </Card>
                </div>

                <div className="col-lg-4 mb-5">
                    <Card className="h-100">
                        <div className="card h-100 shadow-3 hover-shadow-6">
                            <div className="card-body">
                                <h4>Card with list</h4>
                                <p>Aliquam erat volutpat. Aenean tincidunt scelerisque mauris, in pharetra mi venenatis ut.</p>
                                <ul className="list">
                                    <li>Praesent scelerisque</li>
                                    <li>Vestibulum quis</li>
                                    <li>Mauris odio</li>
                                    <li>Integer</li>
                                </ul>
                            </div>
                        </div>
                    </Card>
                </div>
            </div>

            <div className="row">
                <div className="col-lg-6 mb-5">
                    <Card className="h-100">
                        <div className="card h-100 shadow-3 hover-shadow-6">
                            <div className="card-body">
                                <Tabs className="m-0 w-100">
                                    <TabItem label="Tab 1">
                                        <h4>Card with tabs</h4>
                                        <p>Nulla tempus neque id eros blandit, id congue sem ultricies. Nulla molestie viverra aliquet. Praesent feugiat mollis lacus, quis sagittis leo.</p>
                                        <Button className="primary">Sample button</Button>
                                    </TabItem>

                                    <TabItem label="Tab 2">
                                        <h4>Card with tabs</h4>
                                        <p>Nunc lacus mi, fringilla et dignissim eu, pharetra sit amet sapien. Praesent lectus tellus, iaculis ut commodo id, auctor quis velit.</p>
                                        <Button className="primary">Sample button 2</Button>
                                    </TabItem>

                                    <TabItem label="Tab 3">
                                        <h4>Card with tabs</h4>
                                        <p>Aenean et viverra nibh. Sed aliquam facilisis libero, quis lacinia metus gravida ac. Curabitur vitae turpis accumsan diam malesuada placerat quis in felis.</p>
                                        <Button className="primary">Sample button 3</Button>
                                    </TabItem>
                                </Tabs>
                            </div>
                        </div>
                    </Card>
                </div>

                <div className="col-lg-6 mb-5">
                    <Card className="h-100">
                        <div className="card h-100 shadow-3 hover-shadow-6">
                            <div className="card-body">
                                <Tabs className="m-0 w-100" id="pills">
                                    <TabItem label="Pill 1">
                                        <h4>Card with pills</h4>
                                        <p>Nulla tempus neque id eros blandit, id congue sem ultricies. Nulla molestie viverra aliquet. Praesent feugiat mollis lacus, quis sagittis leo.</p>
                                        <Button className="primary">Sample button</Button>
                                    </TabItem>

                                    <TabItem label="Pill 2">
                                        <h4>Card with pills</h4>
                                        <p>Nunc lacus mi, fringilla et dignissim eu, pharetra sit amet sapien. Praesent lectus tellus, iaculis ut commodo id, auctor quis velit.</p>
                                        <Button className="primary">Sample button 2</Button>
                                    </TabItem>

                                    <TabItem label="Pill 3">
                                        <h4>Card with pills</h4>
                                        <p>Aenean et viverra nibh. Sed aliquam facilisis libero, quis lacinia metus gravida ac. Curabitur vitae turpis accumsan diam malesuada placerat quis in felis.</p>
                                        <Button className="primary">Sample button 3</Button>
                                    </TabItem>
                                </Tabs>
                            </div>
                        </div>
                    </Card>

                </div>
            </div>
        </div>
    )
}

export default withAnimation(Cards)
