// templates/admin-template-react/src/Pages/UIElements/Tabs/Tabs.js
import './Tabs.scss';
import { useEffect } from 'react';

import withAnimation from '../../../hoc/withAnimation';

import { defaultTitle } from '../../../contexts/themeContext';

import { Tabs, TabItem } from '../../../smartImports';

function TabsPage() {

    useEffect(() => { document.title = `Tabs - ${defaultTitle}` }, []);

    const homeTemplate = `<span class="material-icons">home</span>`;
    const profileTemplate = `<span class="material-icons">settings</span>`;
    const messagesTemplate = `<span class="material-icons">message</span>`;

    return (
        <div className="container tabs-page">
            <div className="row">
                <div className="col-12 mb-3"><h4>Tabs</h4></div>
            </div>

            <div className="row">
                <div className="col-lg-6 mb-5">
                    <div className="card h-100">
                        <div className="card-header">
                            <h4 className="label">Default tabs</h4>
                        </div>
                        <div className="card-body">
                            <Tabs className="w-100">
                                <TabItem label="Home">
                                    <h6>Default tabs</h6>
                                    <p>Nulla id vestibulum tortor. Vestibulum quis ante lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ac quam quis sem sodales vestibulum.</p>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                                </TabItem>

                                <TabItem label="Profile">
                                    <h6>Profile tab</h6>
                                    <p>Proin venenatis dignissim tortor vel mattis.</p>
                                    <p>Suspendisse pulvinar massa eu massa vestibulum imperdiet.</p>
                                    <p>Aenean fringilla sodales diam eget auctor. Nullam suscipit a leo nec blandit. Aenean suscipit dolor arcu.</p>
                                </TabItem>

                                <TabItem label="Messages">
                                    <h6>Messages tabs</h6>
                                    <p>Etiam orci nunc, ornare sed rhoncus quis, facilisis venenatis neque. Vivamus in nisi elit. Nullam rhoncus nisi purus, sed egestas arcu hendrerit vel.</p>
                                </TabItem>
                            </Tabs>
                        </div>
                    </div>
                </div>

                <div className="col-lg-6 mb-5">
                    <div className="card h-100">
                        <div className="card-header">
                            <h4 className="label">Colored tabs</h4>
                        </div>

                        <div className="card-body">
                            <Tabs className="colored top w-100">
                                <TabItem label="Home">
                                    <h6>Colored tabs</h6>
                                    <p>Nulla id vestibulum tortor. Vestibulum quis ante lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ac quam quis sem sodales vestibulum.</p>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                                </TabItem>

                                <TabItem label="Profile">
                                    <h6>Profile tab</h6>
                                    <p>Proin venenatis dignissim tortor vel mattis.</p>
                                    <p>Suspendisse pulvinar massa eu massa vestibulum imperdiet.</p>
                                    <p>Aenean fringilla sodales diam eget auctor. Nullam suscipit a leo nec blandit. Aenean suscipit dolor arcu.</p>
                                </TabItem>

                                <TabItem label="Messages">
                                    <h6>Messages tabs</h6>
                                    <p>Etiam orci nunc, ornare sed rhoncus quis, facilisis venenatis neque. Vivamus in nisi elit. Nullam rhoncus nisi purus, sed egestas arcu hendrerit vel.</p>
                                </TabItem>
                            </Tabs>
                        </div>
                    </div>
                </div>
            </div>

            <div className="row">
                <div className="col-lg-6 mb-5">
                    <div className="card h-100">
                        <div className="card-header">
                            <h4 className="label">Icon tabs</h4>
                        </div>

                        <div className="card-body">
                            <Tabs className="w-100">
                                <TabItem label={homeTemplate}>
                                    <h6>Icon tabs</h6>
                                    <p>Nulla id vestibulum tortor. Vestibulum quis ante lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ac quam quis sem sodales vestibulum.</p>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                                </TabItem>

                                <TabItem label={profileTemplate}>
                                    <h6>Profile tab</h6>
                                    <p>Proin venenatis dignissim tortor vel mattis.</p>
                                    <p>Suspendisse pulvinar massa eu massa vestibulum imperdiet.</p>
                                    <p>Aenean fringilla sodales diam eget auctor. Nullam suscipit a leo nec blandit. Aenean suscipit dolor arcu.</p>
                                </TabItem>

                                <TabItem label={messagesTemplate}>
                                    <h6>Messages tabs</h6>
                                    <p>Etiam orci nunc, ornare sed rhoncus quis, facilisis venenatis neque. Vivamus in nisi elit. Nullam rhoncus nisi purus, sed egestas arcu hendrerit vel.</p>
                                </TabItem>
                            </Tabs>
                        </div>
                    </div>
                </div>

                <div className="col-lg-6 mb-5">
                    <div className="card h-100">
                        <div className="card-header">
                            <h4 className="label">Colored icon tabs</h4>
                        </div>

                        <div className="card-body">
                            <Tabs className="colored top success w-100">
                                <TabItem label={homeTemplate}>
                                    <h6>Colored icon tabs</h6>
                                    <p>Nulla id vestibulum tortor. Vestibulum quis ante lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ac quam quis sem sodales vestibulum.</p>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                                </TabItem>

                                <TabItem label={profileTemplate}>
                                    <h6>Profile tab</h6>
                                    <p>Proin venenatis dignissim tortor vel mattis.</p>
                                    <p>Suspendisse pulvinar massa eu massa vestibulum imperdiet.</p>
                                    <p>Aenean fringilla sodales diam eget auctor. Nullam suscipit a leo nec blandit. Aenean suscipit dolor arcu.</p>
                                </TabItem>

                                <TabItem label={messagesTemplate}>
                                    <h6>Messages tabs</h6>
                                    <p>Etiam orci nunc, ornare sed rhoncus quis, facilisis venenatis neque. Vivamus in nisi elit. Nullam rhoncus nisi purus, sed egestas arcu hendrerit vel.</p>
                                </TabItem>
                            </Tabs>
                        </div>
                    </div>
                </div>
            </div>

            <div className="row">
                <div className="col-lg-6 mb-5">
                    <div className="card h-100">
                        <div className="card-header">
                            <h4 className="label">Vertical icon tabs</h4>
                        </div>
                        <div className="card-body">
                            <Tabs className="w-100" tab-position="left">
                                <TabItem label={homeTemplate}>
                                    <h6>Vertical icon tabs</h6>
                                    <p>Nulla id vestibulum tortor. Vestibulum quis ante lorem. Lorem ipsum dolor sit amet,
                                        consectetur adipiscing elit. Phasellus ac quam quis sem sodales vestibulum.</p>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                                </TabItem>
                                <TabItem label={profileTemplate}>
                                    <h6>Profile tab</h6>
                                    <p>Proin venenatis dignissim tortor vel mattis.</p>
                                    <p>Suspendisse pulvinar massa eu massa vestibulum imperdiet.</p>
                                    <p>Aenean fringilla sodales diam eget auctor. Nullam suscipit a leo nec blandit. Aenean suscipit
                                        dolor arcu.</p>
                                </TabItem>
                                <TabItem label={messagesTemplate}>
                                    <h6>Messages tabs</h6>
                                    <p>Etiam orci nunc, ornare sed rhoncus quis, facilisis venenatis neque. Vivamus in nisi elit.
                                        Nullam rhoncus nisi purus, sed egestas arcu hendrerit vel.</p>
                                </TabItem>
                            </Tabs>
                        </div>
                    </div>
                </div>

                <div className="col-lg-6 mb-5">
                    <div className="card h-100">
                        <div className="card-header">
                            <h4 className="label">Colored vertical icon tabs</h4>
                        </div>
                        <div className="card-body">
                            <Tabs className="colored left error w-100" tab-position="left">
                                <TabItem label={homeTemplate}>
                                    <h6>Colored vertical icon tabs</h6>
                                    <p>Nulla id vestibulum tortor. Vestibulum quis ante lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ac quam quis sem sodales vestibulum.</p>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                                </TabItem>
                                <TabItem label={profileTemplate}>
                                    <h6>Profile tab</h6>
                                    <p>Proin venenatis dignissim tortor vel mattis.</p>
                                    <p>Suspendisse pulvinar massa eu massa vestibulum imperdiet.</p>
                                    <p>Aenean fringilla sodales diam eget auctor. Nullam suscipit a leo nec blandit. Aenean suscipit dolor arcu.</p>
                                </TabItem>
                                <TabItem label={messagesTemplate}>
                                    <h6>Messages tabs</h6>
                                    <p>Etiam orci nunc, ornare sed rhoncus quis, facilisis venenatis neque. Vivamus in nisi elit. Nullam rhoncus nisi purus, sed egestas arcu hendrerit vel.</p>
                                </TabItem>
                            </Tabs>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default withAnimation(TabsPage)

// templates/admin-template-angular/src/app/pages/ui-elements/tabs/tabs.component.ts
import { Component, OnInit, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'sm-tabs',
  templateUrl: './tabs.component.html',
  styleUrls: ['./tabs.component.scss'],
  encapsulation: ViewEncapsulation.None
})
export class TabsComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="container tabs">
    <div class="custom-row">
        <div class="tabs-header custom-col"><h4>Tabs</h4></div>
    </div>

    <div class="custom-row">
        <div class="tabs-entity custom-col">
            <div class="custom-card h-100">
                <div class="card-header">
                    <h4 class="label">Default tabs</h4>
                </div>
                <div class="card-body">
                    <smart-tabs>
                        <smart-tab-item label="Home">
                            <h6>Default tabs</h6>
                            <p>Nulla id vestibulum tortor. Vestibulum quis ante lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ac quam quis sem sodales vestibulum.</p>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                        </smart-tab-item>

                        <smart-tab-item label="Profile">
                            <h6>Profile tab</h6>
                            <p>Proin venenatis dignissim tortor vel mattis.</p>
                            <p>Suspendisse pulvinar massa eu massa vestibulum imperdiet.</p>
                            <p>Aenean fringilla sodales diam eget auctor. Nullam suscipit a leo nec blandit. Aenean suscipit dolor arcu.</p>
                        </smart-tab-item>

                        <smart-tab-item label="Messages">
                            <h6>Messages tabs</h6>
                            <p>Etiam orci nunc, ornare sed rhoncus quis, facilisis venenatis neque. Vivamus in nisi elit. Nullam rhoncus nisi purus, sed egestas arcu hendrerit vel.</p>
                        </smart-tab-item>
                    </smart-tabs>
                </div>
            </div>
        </div>

        <div class="tabs-entity custom-col">
            <div class="custom-card h-100">
                <div class="card-header">
                    <h4 class="label">Colored tabs</h4>
                </div>

                <div class="card-body">
                    <smart-tabs class="colored top">
                        <smart-tab-item label="Home">
                            <h6>Colored tabs</h6>
                            <p>Nulla id vestibulum tortor. Vestibulum quis ante lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ac quam quis sem sodales vestibulum.</p>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                        </smart-tab-item>

                        <smart-tab-item label="Profile">
                            <h6>Profile tab</h6>
                            <p>Proin venenatis dignissim tortor vel mattis.</p>
                            <p>Suspendisse pulvinar massa eu massa vestibulum imperdiet.</p>
                            <p>Aenean fringilla sodales diam eget auctor. Nullam suscipit a leo nec blandit. Aenean suscipit dolor arcu.</p>
                        </smart-tab-item>

                        <smart-tab-item label="Messages">
                            <h6>Messages tabs</h6>
                            <p>Etiam orci nunc, ornare sed rhoncus quis, facilisis venenatis neque. Vivamus in nisi elit. Nullam rhoncus nisi purus, sed egestas arcu hendrerit vel.</p>
                        </smart-tab-item>
                    </smart-tabs>
                </div>
            </div>
        </div>
    </div>

    <div class="custom-row">
        <div class="tabs-entity custom-col">
            <div class="custom-card h-100">
                <div class="card-header">
                    <h4 class="label">Icon tabs</h4>
                </div>

                <div class="card-body">
                    <smart-tabs>
                        <smart-tab-item label="homeTemplate">
                            <h6>Icon tabs</h6>
                            <p>Nulla id vestibulum tortor. Vestibulum quis ante lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ac quam quis sem sodales vestibulum.</p>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                        </smart-tab-item>

                        <smart-tab-item label="profileTemplate">
                            <h6>Profile tab</h6>
                            <p>Proin venenatis dignissim tortor vel mattis.</p>
                            <p>Suspendisse pulvinar massa eu massa vestibulum imperdiet.</p>
                            <p>Aenean fringilla sodales diam eget auctor. Nullam suscipit a leo nec blandit. Aenean suscipit dolor arcu.</p>
                        </smart-tab-item>

                        <smart-tab-item label="messagesTemplate">
                            <h6>Messages tabs</h6>
                            <p>Etiam orci nunc, ornare sed rhoncus quis, facilisis venenatis neque. Vivamus in nisi elit. Nullam rhoncus nisi purus, sed egestas arcu hendrerit vel.</p>
                        </smart-tab-item>
                    </smart-tabs>
                </div>
            </div>
        </div>

        <div class="tabs-entity custom-col">
            <div class="custom-card h-100">
                <div class="card-header">
                    <h4 class="label">Colored icon tabs</h4>
                </div>

                <div class="card-body">
                    <smart-tabs class="colored top success">
                        <smart-tab-item label="homeTemplate">
                            <h6>Colored icon tabs</h6>
                            <p>Nulla id vestibulum tortor. Vestibulum quis ante lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ac quam quis sem sodales vestibulum.</p>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                        </smart-tab-item>

                        <smart-tab-item label="profileTemplate">
                            <h6>Profile tab</h6>
                            <p>Proin venenatis dignissim tortor vel mattis.</p>
                            <p>Suspendisse pulvinar massa eu massa vestibulum imperdiet.</p>
                            <p>Aenean fringilla sodales diam eget auctor. Nullam suscipit a leo nec blandit. Aenean suscipit dolor arcu.</p>
                        </smart-tab-item>

                        <smart-tab-item label="messagesTemplate">
                            <h6>Messages tabs</h6>
                            <p>Etiam orci nunc, ornare sed rhoncus quis, facilisis venenatis neque. Vivamus in nisi elit. Nullam rhoncus nisi purus, sed egestas arcu hendrerit vel.</p>
                        </smart-tab-item>
                    </smart-tabs>
                </div>
            </div>
        </div>
    </div>

    <div class="custom-row">
        <div class="tabs-entity custom-col">
            <div class="custom-card h-100">
                <div class="card-header">
                    <h4 class="label">Vertical icon tabs</h4>
                </div>
                <div class="card-body">
                    <smart-tabs tab-position="left">
                        <smart-tab-item label="homeTemplate">
                            <h6>Vertical icon tabs</h6>
                            <p>Nulla id vestibulum tortor. Vestibulum quis ante lorem. Lorem ipsum dolor sit amet,
                                consectetur adipiscing elit. Phasellus ac quam quis sem sodales vestibulum.</p>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                        </smart-tab-item>
                        <smart-tab-item label="profileTemplate">
                            <h6>Profile tab</h6>
                            <p>Proin venenatis dignissim tortor vel mattis.</p>
                            <p>Suspendisse pulvinar massa eu massa vestibulum imperdiet.</p>
                            <p>Aenean fringilla sodales diam eget auctor. Nullam suscipit a leo nec blandit. Aenean suscipit
                                dolor arcu.</p>
                        </smart-tab-item>
                        <smart-tab-item label="messagesTemplate">
                            <h6>Messages tabs</h6>
                            <p>Etiam orci nunc, ornare sed rhoncus quis, facilisis venenatis neque. Vivamus in nisi elit.
                                Nullam rhoncus nisi purus, sed egestas arcu hendrerit vel.</p>
                        </smart-tab-item>
                    </smart-tabs>
                </div>
            </div>
        </div>

        <div class="tabs-entity custom-col">
            <div class="custom-card h-100">
                <div class="card-header">
                    <h4 class="label">Colored vertical icon tabs</h4>
                </div>
                <div class="card-body">
                    <smart-tabs class="colored left error" tab-position="left">
                        <smart-tab-item label="homeTemplate">
                            <h6>Colored vertical icon tabs</h6>
                            <p>Nulla id vestibulum tortor. Vestibulum quis ante lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ac quam quis sem sodales vestibulum.</p>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                        </smart-tab-item>
                        <smart-tab-item label="profileTemplate">
                            <h6>Profile tab</h6>
                            <p>Proin venenatis dignissim tortor vel mattis.</p>
                            <p>Suspendisse pulvinar massa eu massa vestibulum imperdiet.</p>
                            <p>Aenean fringilla sodales diam eget auctor. Nullam suscipit a leo nec blandit. Aenean suscipit dolor arcu.</p>
                        </smart-tab-item>
                        <smart-tab-item label="messagesTemplate">
                            <h6>Messages tabs</h6>
                            <p>Etiam orci nunc, ornare sed rhoncus quis, facilisis venenatis neque. Vivamus in nisi elit. Nullam rhoncus nisi purus, sed egestas arcu hendrerit vel.</p>
                        </smart-tab-item>
                    </smart-tabs>
                </div>
            </div>
        </div>
    </div>
</div>

<template id="homeTemplate"><span class="material-icons">home</span></template>
<template id="profileTemplate"><span class="material-icons">settings</span></template>
<template id="messagesTemplate"><span class="material-icons">message</span></template>
