// templates/admin-template-angular/src/app/pages/applications/e-commerce/ecommerce-dashboard/ecommerce-dashboard.component.ts
import { AfterViewInit, Component, ViewChild, ViewEncapsulation } from '@angular/core';
import { Menu } from 'smart-webcomponents-angular';
import { ChartComponent } from 'smart-webcomponents-angular/chart';
import { StylingService } from 'src/app/services/styling.service';

@Component({
  selector: 'sm-ecommerce-dashboard',
  templateUrl: './ecommerce-dashboard.component.html',
  styleUrls: ['./ecommerce-dashboard.component.scss'],
  encapsulation: ViewEncapsulation.None
})
export class EcommerceDashboardComponent implements AfterViewInit {

  @ViewChild('revenueChart', { read: ChartComponent, static: false }) revenueChart!: ChartComponent;
  @ViewChild('salesComparisonChart', { read: ChartComponent, static: false }) salesComparisonChart!: ChartComponent;

  salesData = [
    { month: 'Jan', sales: 22330, orders: 9302 },
    { month: 'Feb', sales: 21323, orders: 8902 },
    { month: 'Mar', sales: 28200, orders: 10043 },
    { month: 'Apr', sales: 31889, orders: 10992 },
    { month: 'May', sales: 30056, orders: 9980 },
    { month: 'Jun', sales: 42024, orders: 13489 },
    { month: 'Jul', sales: 44995, orders: 19048 },
    { month: 'Aug', sales: 41045, orders: 12334 },
    { month: 'Sep', sales: 38012, orders: 11102 },
    { month: 'Oct', sales: 40045, orders: 11894 },
    { month: 'Nov', sales: 27542, orders: 8301 },
    { month: 'Dec', sales: 29012, orders: 10632 }
  ];

  salesComparisonData = [
    { month: 'Jan', current: 77, last: 98 },
    { month: 'Feb', current: 70, last: 89 },
    { month: 'Mar', current: 67, last: 79 },
    { month: 'Apr', current: 82, last: 81 },
    { month: 'May', current: 93, last: 99 },
    { month: 'Jun', current: 112, last: 122 },
    { month: 'Jul', current: 130, last: 129 },
    { month: 'Aug', current: 118, last: 125 },
    { month: 'Sep', current: 92, last: 99 },
    { month: 'Oct', current: 75, last: 83 },
    { month: 'Nov', current: 78, last: 90 },
    { month: 'Dec', current: 90, last: 112 }
  ];

  bestSellingData = [
    { name: 'UX-Generator', language: 'JavaScript', sales: 54000 },
    { name: 'Smart HTML Elements', language: 'JavaScript', sales: 163030 },
    { name: 'Hawk UI', language: 'C#', sales: 13000 },
    { name: 'Styler-CSS', language: 'CSS', sales: 3400 },
    { name: 'TypeWriterJS', language: 'TypeScript', sales: 18900 },
    { name: 'UX-Paradigm', language: 'JavaScript', sales: 920 },
    { name: 'Mobile-enhancer', language: 'CSS', sales: 7570 },
    { name: 'Async-script', language: 'Java', sales: 15030 }
  ];

  customColors = [
    this.styling.getComputedStyleVars('primary'),
    this.styling.getComputedStyleVars('info'),
    this.styling.getComputedStyleVars('warning'),
    this.styling.getComputedStyleVars('success'),
    this.styling.getComputedStyleVars('danger'),
    this.styling.getComputedStyleVars('secondary')
  ];

  theme = this.styling.getTheme();

  revenueChartData = {
    theme: this.theme,
    padding: { left: 5, top: 15, right: 25, bottom: 5 },
    dataSource: this.salesData,
    xAxis: {
      dataField: 'month',
      displayText: 'Month'
    },
    colorScheme: 'custom',
    seriesGroups: [
      {
        type: 'spline',
        valueAxis: {
          labels: {
            horizontalAlignment: 'right',
            formatSettings: { decimalPlaces: 0 }
          },
          gridLines: {
            visible: false
          }
        },
        series: [
          { dataField: 'sales', displayText: 'Sales ($)', symbolSize: 8, symbolType: 'circle' },
          { dataField: 'orders', displayText: 'Orders', symbolSize: 8, symbolType: 'circle', dashStyle: '5,4' }
        ]
      }
    ]
  }

  salesComparisonChartData = {
    padding: { left: 5, top: 15, right: 25, bottom: 5 },
    dataSource: this.salesComparisonData,
    colorScheme: 'custom',
    xAxis: {
      dataField: 'month',
      displayText: 'Month',
      gridLines: {
        visible: false
      }
    },
    seriesGroups: [
      {
        type: 'column',
        valueAxis: {
          labels: {
            horizontalAlignment: 'right',
            formatSettings: { decimalPlaces: 0 }
          },
          gridLines: {
            visible: false
          }
        },
        series: [
          { dataField: 'last', displayText: 'Last year' },
          { dataField: 'current', displayText: 'This year' }
        ]
      }
    ]
  }

  bestSellingTableData = {
    dataSource: this.bestSellingData,
    sortMode: 'one',
    columns: [
      { label: 'Product Name', dataField: 'name', dataType: 'string' },
      {
        label: 'Language', dataField: 'language', dataType: 'string', formatFunction(settings: any) {
          const value = settings.value;

          settings.template = `<span class="smart-badge smart-badge-pill ${value.replace('#', '-sharp').toLowerCase()}"">${value}</span>`;
        }
      },
      { label: 'Sales', dataField: 'sales', dataType: 'number' }
    ]
  }
  constructor(private styling: StylingService) { }

  ngAfterViewInit(): void {

    this.revenueChart.addColorScheme('custom', this.customColors);
    this.revenueChart.refresh();

    this.salesComparisonChart.addColorScheme('custom', this.customColors);
    this.salesComparisonChart.refresh();
  }

  stopPropagation(e: Event) {
    e.stopPropagation();
  }

  toggleMenu(button: HTMLElement) {

    const todayMenu = document.querySelector('#todayMenu') as Menu;
    const rect = button.getBoundingClientRect();

    Array.from(document.getElementsByTagName('smart-menu'))
      .filter(currentMenu => currentMenu !== todayMenu)
      .forEach(currentMenu => currentMenu.close());

    document.querySelectorAll('.dropdown-menu-show').forEach(e => {
      e.classList.remove('dropdown-menu-show');
    })

    document.querySelectorAll('.dropdown-button')
      .forEach(menu => menu.classList.remove('dropdown-button-active'));

    if (!todayMenu.opened) {

      todayMenu.open(rect.right - todayMenu.offsetWidth, rect.bottom + window.scrollY);

    } else {

      todayMenu.close();

    }

  }
}

<div class="container e-commerce-dashboard">
    <div class="custom-row">
        <div class="custom-col">
            <div class="header-menu">
                <div class="welcome">Welcome back, John!</div>
                <smart-button class="today-button settings-button"><span
                        class="material-icons">calendar_today</span>Today<span
                        class="material-icons">keyboard_arrow_down</span></smart-button>
                <smart-button class="primary"><span class="material-icons">filter_alt</span></smart-button>
                <smart-button class="primary"><span class="material-icons">refresh</span></smart-button>
            </div>
        </div>
    </div>

    <div class="custom-row">
        <div class="custom-col progress-card-col">
            <div class="custom-card h-100">
                <div class="card-body">
                    <div class="custom-row margin-bottom-1-5">
                        <div class="custom-col col-full">
                            <h6 class="font-weight-bold mb-0">Income</h6>
                        </div>
                        <div class="custom-col col-full text-right">
                            <span class="smart-badge smart-badge-info">Today</span>
                        </div>
                    </div>

                    <div class="custom-row margin-bottom-1-5">
                        <div class="custom-col col-full">
                            <h5 class="mb-0">$53.305</h5>
                        </div>
                        <div class="custom-col col-full text-right">
                            <span class="">91%</span>
                        </div>
                    </div>

                    <div class="custom-row">
                        <div class="custom-col custom-col-12">
                            <smart-progress-bar [value]="91" class="info"></smart-progress-bar>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="custom-col progress-card-col">
            <div class="custom-card h-100">
                <div class="card-body">
                    <div class="custom-row margin-bottom-1-5">
                        <div class="custom-col col-full">
                            <h6 class="font-weight-bold mb-0">Orders</h6>
                        </div>
                        <div class="custom-col col-full text-right">
                            <span class="smart-badge smart-badge-warning">Annual</span>
                        </div>
                    </div>

                    <div class="custom-row margin-bottom-1-5">
                        <div class="custom-col col-full">
                            <h5 class="mb-0">9.809</h5>
                        </div>
                        <div class="custom-col col-full text-right">
                            <span class="">23%</span>
                        </div>
                    </div>

                    <div class="custom-row">
                        <div class="custom-col custom-col-12">
                            <smart-progress-bar [value]="23" class="warning"></smart-progress-bar>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="custom-col progress-card-col">
            <div class="custom-card h-100">
                <div class="card-body">
                    <div class="custom-row margin-bottom-1-5">
                        <div class="custom-col col-full">
                            <h6 class="font-weight-bold mb-0">Activity</h6>
                        </div>
                        <div class="custom-col col-full text-right">
                            <span class="smart-badge smart-badge-primary">Monthly</span>
                        </div>
                    </div>

                    <div class="custom-row margin-bottom-1-5">
                        <div class="custom-col col-full">
                            <h5 class="mb-0">17.380</h5>
                        </div>
                        <div class="custom-col col-full text-right">
                            <span class="">50%</span>
                        </div>
                    </div>

                    <div class="custom-row">
                        <div class="custom-col custom-col-12">
                            <smart-progress-bar [value]="50" class="primary"></smart-progress-bar>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="custom-col progress-card-col">
            <div class="custom-card h-100">
                <div class="card-body">
                    <div class="custom-row margin-bottom-1-5">
                        <div class="custom-col col-full">
                            <h6 class="font-weight-bold mb-0">Revenue</h6>
                        </div>
                        <div class="custom-col col-full text-right">
                            <span class="smart-badge smart-badge-success">Yearly</span>
                        </div>
                    </div>

                    <div class="custom-row margin-bottom-1-5">
                        <div class="custom-col col-full">
                            <h5 class="mb-0">$28.940</h5>
                        </div>
                        <div class="custom-col col-full text-right">
                            <span class="">41%</span>
                        </div>
                    </div>

                    <div class="custom-row">
                        <div class="custom-col custom-col-12">
                            <smart-progress-bar [value]="41" class="success"></smart-progress-bar>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="custom-row locations-revenue-orderAct">

        <div class="custom-col col-entity-lg-8">
            <div class="custom-card h-100">
                <div class="card-header">
                    <h4 class="label">Total Revenue</h4>
                    <div class="settings-button" #revenueButton (click)="toggleMenu(revenueButton)"
                        (pointerup)="stopPropagation($event)">…</div>
                </div>
                <div class="card-body revenue-chart-wrapper">
                    <smart-chart #revenueChart class="e-commerce-dashboard-revenue-chart" [animation]="'none'"
                        [theme]="theme!" [caption]="'Caption'" [description]="'Description'" [showLegend]="true"
                        [showBorderLine]="true" [padding]="revenueChartData.padding"
                        [dataSource]="revenueChartData.dataSource" [xAxis]="revenueChartData.xAxis"
                        [seriesGroups]="revenueChartData.seriesGroups" [colorScheme]="'custom'"></smart-chart>
                </div>
            </div>
        </div>

        <div class="custom-col col-entity-lg-4">
            <div class="custom-card h-100">
                <div class="card-header">
                    <h4 class="label">Order Activity</h4>
                    <div class="settings-button" #orderActivityButton (click)="toggleMenu(orderActivityButton)"
                        (pointerup)="stopPropagation($event)">…</div>
                </div>

                <div class="card-body maxh-350 p-0">
                    <div class="appointmentContainer h-100">
                        <div class="appointment">
                            <div class="label"><strong>Delivered</strong></div>
                            <p class="">30 minutes ago</p>
                        </div>
                        <div class="appointment">
                            <div class="label"><strong>In transit</strong></div>
                            <p class="">3 hours ago</p>
                        </div>
                        <div class="appointment">
                            <div class="label"><strong>Shipped</strong></div>
                            <p class="">1 day ago</p>
                        </div>
                        <div class="appointment">
                            <div class="label"><strong>Received</strong></div>
                            <p class="">2 days ago</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="custom-row realTime-sales">
        <div class="custom-col col-entity-lg-8">
            <div class="custom-card h-100">
                <div class="card-header">
                    <h4 class="label">Real-Time</h4>
                    <div class="settings-button" #bestSellingTableButton (click)="toggleMenu(bestSellingTableButton)"
                    (pointerup)="stopPropagation($event)">…</div>
                </div>
                <div class="card-body">
                    <smart-table class="e-commerce-bestSellingTable table-striped no-border" [dataSource]="bestSellingTableData.dataSource"
                        [columns]="bestSellingTableData.columns" [sortMode]="'one'"></smart-table>
                </div>
            </div>
        </div>

        <div class="custom-col col-entity-lg-4">
            <div class="custom-card h-100">
                <div class="card-header">
                    <h4 class="label">Sales Comparison</h4>
                    <div class="settings-button" #salesComparisonButton (click)="toggleMenu(salesComparisonButton)"
                    (pointerup)="stopPropagation($event)">…</div>
                </div>
                <div class="card-body">
                    <smart-chart #salesComparisonChart class="e-commerce-dashboard-sales-comparison-chart"
                        [animation]="'none'" [theme]="theme!" [caption]="'Caption'" [description]="'Description'"
                        [showLegend]="true" [showBorderLine]="true" [padding]="salesComparisonChartData.padding"
                        [dataSource]="salesComparisonChartData.dataSource" [xAxis]="salesComparisonChartData.xAxis"
                        [colorScheme]="salesComparisonChartData.colorScheme"
                        [seriesGroups]="salesComparisonChartData.seriesGroups"></smart-chart>
                </div>
            </div>
        </div>
    </div>
</div>

// templates/admin-template-react/src/Pages/Ecommerce/EcommerceDashboard/EcommerceDashboard.js
import './EcommerceDashboard.scss';
import { useEffect, useRef } from 'react';

import withAnimation from '../../../hoc/withAnimation';

import { Button, ProgressBar, Chart, Table } from '../../../smartImports';

import { useThemeContext, defaultTitle } from '../../../contexts/themeContext';

function EcommerceDashboard({ openTodayMenu }) {

    const salesData = [
        { month: 'Jan', sales: 22330, orders: 9302 },
        { month: 'Feb', sales: 21323, orders: 8902 },
        { month: 'Mar', sales: 28200, orders: 10043 },
        { month: 'Apr', sales: 31889, orders: 10992 },
        { month: 'May', sales: 30056, orders: 9980 },
        { month: 'Jun', sales: 42024, orders: 13489 },
        { month: 'Jul', sales: 44995, orders: 19048 },
        { month: 'Aug', sales: 41045, orders: 12334 },
        { month: 'Sep', sales: 38012, orders: 11102 },
        { month: 'Oct', sales: 40045, orders: 11894 },
        { month: 'Nov', sales: 27542, orders: 8301 },
        { month: 'Dec', sales: 29012, orders: 10632 }
    ];

    const bestSellingData = [
        { name: 'UX-Generator', language: 'JavaScript', sales: 54000 },
        { name: 'Smart HTML Elements', language: 'JavaScript', sales: 163030 },
        { name: 'Hawk UI', language: 'C#', sales: 13000 },
        { name: 'Styler-CSS', language: 'CSS', sales: 3400 },
        { name: 'TypeWriterJS', language: 'TypeScript', sales: 18900 },
        { name: 'UX-Paradigm', language: 'JavaScript', sales: 920 },
        { name: 'Mobile-enhancer', language: 'CSS', sales: 7570 },
        { name: 'Async-script', language: 'Java', sales: 15030 }
    ];

    const salesComparisonData = [
        { month: 'Jan', current: 77, last: 98 },
        { month: 'Feb', current: 70, last: 89 },
        { month: 'Mar', current: 67, last: 79 },
        { month: 'Apr', current: 82, last: 81 },
        { month: 'May', current: 93, last: 99 },
        { month: 'Jun', current: 112, last: 122 },
        { month: 'Jul', current: 130, last: 129 },
        { month: 'Aug', current: 118, last: 125 },
        { month: 'Sep', current: 92, last: 99 },
        { month: 'Oct', current: 75, last: 83 },
        { month: 'Nov', current: 78, last: 90 },
        { month: 'Dec', current: 90, last: 112 }
    ];

    const { themeObj, customColors } = useThemeContext();

    const revenueChartRef = useRef(null);
    const salesComparisonChartRef = useRef(null);

    useEffect(() => { document.title = `E-commerce - ${defaultTitle}` }, []);

    useEffect(() => {

        if (customColors) {

            revenueChartRef?.current.addColorScheme('custom', customColors);
            revenueChartRef?.current.refresh();

            salesComparisonChartRef?.current.addColorScheme('custom', customColors);
            salesComparisonChartRef?.current.refresh();

        }

    }, [customColors]);

    const revenueChartData = {
        animation: 'none',
        theme: themeObj.theme,
        caption: 'Caption',
        description: 'Description',
        showLegend: true,
        showBorderLine: true,
        padding: { left: 5, top: 15, right: 25, bottom: 5 },
        dataSource: salesData,
        xAxis: {
            dataField: 'month',
            displayText: 'Month'
        },
        colorScheme: 'custom',
        seriesGroups: [
            {
                type: 'spline',
                valueAxis: {
                    labels: {
                        horizontalAlignment: 'right',
                        formatSettings: { decimalPlaces: 0 }
                    },
                    gridLines: {
                        visible: false
                    }
                },
                series: [
                    { dataField: 'sales', displayText: 'Sales ($)', symbolSize: 8, symbolType: 'circle' },
                    { dataField: 'orders', displayText: 'Orders', symbolSize: 8, symbolType: 'circle', dashStyle: '5,4' }
                ]
            }
        ]
    }

    const bestSellingTableData = {
        dataSource: bestSellingData,
        sortMode: 'one',
        columns: [
            { label: 'Product Name', dataField: 'name', dataType: 'string' },
            {
                label: 'Language', dataField: 'language', dataType: 'string', formatFunction(settings) {
                    const value = settings.value;

                    settings.template = `<span class="smart-badge smart-badge-pill ${value.replace('#', '-sharp').toLowerCase()}"">${value}</span>`;
                }
            },
            { label: 'Sales', dataField: 'sales', dataType: 'number' }
        ]
    }

    const salesComparisonChartData = {
        animation: 'none',
        theme: themeObj.theme,
        caption: 'Caption',
        description: 'Description',
        showLegend: true,
        showBorderLine: true,
        padding: { left: 5, top: 15, right: 25, bottom: 5 },
        dataSource: salesComparisonData,
        xAxis: {
            dataField: 'month',
            displayText: 'Month',
            gridLines: {
                visible: false
            }
        },
        colorScheme: 'custom',
        seriesGroups: [
            {
                type: 'column',
                valueAxis: {
                    labels: {
                        horizontalAlignment: 'right',
                        formatSettings: { decimalPlaces: 0 }
                    },
                    gridLines: {
                        visible: false
                    }
                },
                series: [
                    { dataField: 'last', displayText: 'Last year' },
                    { dataField: 'current', displayText: 'This year' }
                ]
            }
        ]
    }

    return (
        <div className="container e-commerce-dashboard">
            <div className="row">
                <div className="col">
                    <div className="header-menu">
                        <div className="welcome">Welcome back, John!</div>
                        <Button
                            className="today-button settings-button"
                            onClick={(e) => openTodayMenu(e)}
                            onPointerUp={(e) => e.stopPropagation()}
                        >
                            <span className="material-icons">calendar_today</span>
                            Today
                            <span className="material-icons">keyboard_arrow_down</span>
                        </Button>
                        <Button className="primary"><span className="material-icons">filter_alt</span></Button>
                        <Button className="primary"><span className="material-icons">refresh</span></Button>
                    </div>
                </div>
            </div>

            <div className="row">
                <div className="col-sm-6 col-lg-3 mb-5">
                    <div className="card h-100">
                        <div className="card-body">
                            <div className="row justify-content-between align-items-center mb-5">
                                <div className="col">
                                    <h6 className="font-weight-bold mb-0">Income</h6>
                                </div>
                                <div className="col text-right">
                                    <span className="smart-badge smart-badge-info">Today</span>
                                </div>
                            </div>

                            <div className="row justify-content-between align-items-center mb-5">
                                <div className="col">
                                    <h5 className="mb-0">$53.305</h5>
                                </div>
                                <div className="col text-right">
                                    <span className="">91%</span>
                                </div>
                            </div>

                            <div className="row justify-content-between align-items-center">
                                <div className="col-12">
                                    <ProgressBar value={91} className="info"></ProgressBar>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div className="col-sm-6 col-lg-3 mb-5">
                    <div className="card h-100">
                        <div className="card-body">
                            <div className="row justify-content-between align-items-center mb-5">
                                <div className="col">
                                    <h6 className="font-weight-bold mb-0">Orders</h6>
                                </div>
                                <div className="col text-right">
                                    <span className="smart-badge smart-badge-warning">Annual</span>
                                </div>
                            </div>

                            <div className="row justify-content-between align-items-center mb-5">
                                <div className="col">
                                    <h5 className="mb-0">9.809</h5>
                                </div>
                                <div className="col text-right">
                                    <span className="">23%</span>
                                </div>
                            </div>

                            <div className="row justify-content-between align-items-center">
                                <div className="col-12">
                                    <ProgressBar value={23} className="warning"></ProgressBar>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div className="col-sm-6 col-lg-3 mb-5">
                    <div className="card h-100">
                        <div className="card-body">
                            <div className="row justify-content-between align-items-center mb-5">
                                <div className="col">
                                    <h6 className="font-weight-bold mb-0">Activity</h6>
                                </div>
                                <div className="col text-right">
                                    <span className="smart-badge smart-badge-primary">Monthly</span>
                                </div>
                            </div>

                            <div className="row justify-content-between align-items-center mb-5">
                                <div className="col">
                                    <h5 className="mb-0">17.380</h5>
                                </div>
                                <div className="col text-right">
                                    <span className="">50%</span>
                                </div>
                            </div>

                            <div className="row justify-content-between align-items-center">
                                <div className="col-12">
                                    <ProgressBar value={50} className="primary"></ProgressBar>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div className="col-sm-6 col-lg-3 mb-5">
                    <div className="card h-100">
                        <div className="card-body">
                            <div className="row justify-content-between align-items-center mb-5">
                                <div className="col">
                                    <h6 className="font-weight-bold mb-0">Revenue</h6>
                                </div>
                                <div className="col text-right">
                                    <span className="smart-badge smart-badge-success">Yearly</span>
                                </div>
                            </div>

                            <div className="row justify-content-between align-items-center mb-5">
                                <div className="col">
                                    <h5 className="mb-0">$28.940</h5>
                                </div>
                                <div className="col text-right">
                                    <span className="">41%</span>
                                </div>
                            </div>

                            <div className="row justify-content-between align-items-center">
                                <div className="col-12">
                                    <ProgressBar value={41} className="success"></ProgressBar>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div className="row">
                <div className="col-lg-6 mb-5">
                    <div className="card h-100">
                        <div className="card-header">
                            <h4 className="label">Total Revenue</h4>
                            <div
                                className="settings-button"
                                onClick={(e) => openTodayMenu(e)}
                                onPointerUp={(e) => e.stopPropagation()}
                            >…</div>
                        </div>
                        <div className="card-body maxh-350">
                            <Chart
                                ref={revenueChartRef}
                                {...revenueChartData}
                                id="revenueChart"
                                className='h-100 w-100'
                            >
                            </Chart>
                        </div>
                    </div>
                </div>

                <div className="col-lg-6 mb-5">
                    <div className="card h-100">
                        <div className="card-header">
                            <h4 className="label">Order Activity</h4>
                            <div
                                className="settings-button"
                                onClick={(e) => openTodayMenu(e)}
                                onPointerUp={(e) => e.stopPropagation()}
                            >…</div>
                        </div>

                        <div className="card-body maxh-350 p-0">
                            <div id="appointmentContainer" className="h-100">
                                <div className="appointment">
                                    <div className="label"><strong>Delivered</strong></div>
                                    <p className="">30 minutes ago</p>
                                </div>
                                <div className="appointment">
                                    <div className="label"><strong>In transit</strong></div>
                                    <p className="">3 hours ago</p>
                                </div>
                                <div className="appointment">
                                    <div className="label"><strong>Shipped</strong></div>
                                    <p className="">1 day ago</p>
                                </div>
                                <div className="appointment">
                                    <div className="label"><strong>Received</strong></div>
                                    <p className="">2 days ago</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div className="row">
                <div className="col-lg-8 mb-5">
                    <div className="card h-100">
                        <div className="card-header">
                            <h4 className="label">Real-Time</h4>
                            <div
                                className="settings-button"
                                onClick={(e) => openTodayMenu(e)}
                                onPointerUp={(e) => e.stopPropagation()}
                            >…</div>
                        </div>
                        <div className="card-body">
                            <Table
                                id="bestSellingTable"
                                className="table-striped no-border maxh-300"
                                {...bestSellingTableData}
                            ></Table>
                        </div>
                    </div>
                </div>

                <div className="col-lg-4 mb-5">
                    <div className="card h-100">
                        <div className="card-header">
                            <h4 className="label">Sales Comparison</h4>
                            <div
                                className="settings-button"
                                onClick={(e) => openTodayMenu(e)}
                                onPointerUp={(e) => e.stopPropagation()}
                            >…</div>
                        </div>
                        <div className="card-body">
                            <Chart
                                ref={salesComparisonChartRef}
                                {...salesComparisonChartData}
                                id="salesComparisonChart"
                                className='h-100 w-100'
                            >
                            </Chart>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default withAnimation(EcommerceDashboard)
