// templates/admin-template-angular/src/app/pages/applications/profile/account-settings/account-settings.component.ts
import { AfterViewInit, Component, ElementRef, OnInit, ViewChild, ViewEncapsulation } from '@angular/core';
import { Menu } from 'smart-webcomponents-angular';

@Component({
  selector: 'sm-account-settings',
  templateUrl: './account-settings.component.html',
  styleUrls: ['./account-settings.component.scss'],
  encapsulation: ViewEncapsulation.None
})
export class AccountSettingsComponent implements AfterViewInit {

  @ViewChild('accountTemplate') accountTemplateRef!: ElementRef;
  @ViewChild('passwordTemplate') passwordTemplateRef!: ElementRef;
  @ViewChild('mainCol') mainColRef!: ElementRef;

  currentView = 'accountTemplate';

  constructor() { }

  ngAfterViewInit(): void {

    const mainCol: HTMLElement = this.mainColRef.nativeElement;

    mainCol.addEventListener('transitionend', () => {

      const accountTemplate: HTMLElement = this.accountTemplateRef.nativeElement;
      const passwordTemplate: HTMLElement = this.passwordTemplateRef.nativeElement;

      if (this.currentView === 'accountTemplate') {
        passwordTemplate.style.display = 'none';
        accountTemplate.style.display = 'block';
      } else if (this.currentView === 'passwordTemplate') {
        passwordTemplate.style.display = 'block';
        accountTemplate.style.display = 'none';
      }

      mainCol.classList.remove('changing');

    })
  }

  onListBoxChange(event: CustomEvent) {

    const mainCol: HTMLElement = this.mainColRef.nativeElement;

    if (event.detail.selected && event.detail.index < 2) {

      mainCol.classList.add('changing');

      if (event.detail.index === 0) {

        this.currentView = 'accountTemplate';

      }

      else if (event.detail.index === 1) {

        this.currentView = 'passwordTemplate'

      }

    }
  }

  stopPropagation(e: Event) {
    e.stopPropagation();
  }

  toggleMenu(button: HTMLElement) {

    const todayMenu = document.querySelector('#todayMenu') as Menu;
    const rect = button.getBoundingClientRect();

    Array.from(document.getElementsByTagName('smart-menu'))
      .filter(currentMenu => currentMenu !== todayMenu)
      .forEach(currentMenu => currentMenu.close());

    document.querySelectorAll('.dropdown-menu-show').forEach(e => {
      e.classList.remove('dropdown-menu-show');
    })

    document.querySelectorAll('.dropdown-button')
      .forEach(menu => menu.classList.remove('dropdown-button-active'));

    if (!todayMenu.opened) {

      todayMenu.open(rect.right - todayMenu.offsetWidth, rect.bottom + window.scrollY);

    } else {

      todayMenu.close();

    }

  }
}

<div class="container account-settings">
    <div class="custom-row">
        <div class="custom-col col-entity-12" style="margin-bottom: 0.75rem;">
            <h4>Settings</h4>
        </div>
    </div>

    <div class="custom-row">
        <div class="custom-col col-entity-lg-4 mb-5">
            <div class="custom-card">
                <div class="card-header">
                    <h4 class="label">Profile Settings</h4>
                </div>

                <div class="card-body">
                    <smart-list-box id="settingsListBox" (onChange)="onListBoxChange($event)">
                        <smart-list-item [selected]="true">Account</smart-list-item>
                        <smart-list-item>Password</smart-list-item>
                        <smart-list-item>Privacy and safety</smart-list-item>
                        <smart-list-item>Email notifications</smart-list-item>
                        <smart-list-item>Web notifications</smart-list-item>
                        <smart-list-item>Widgets</smart-list-item>
                        <smart-list-item>Your data</smart-list-item>
                        <smart-list-item>Delete account</smart-list-item>
                    </smart-list-box>
                </div>
            </div>
        </div>

        <div #mainCol id="mainCol" class="custom-col col-entity-lg-8">
            <div #accountTemplate id="accountTemplate">
                <div class="custom-card">
                    <div class="card-header">
                        <h4 class="label">Public info</h4>
                        <div class="settings-button" #publicInfoButton (click)="toggleMenu(publicInfoButton)"
                        (pointerup)="stopPropagation($event)">…</div>
                    </div>

                    <div class="card-body">
                        <div id="publicInfoContainer" class="custom-row d-flex">
                            <div class="custom-col col-entity-md-8 order-2 order-md-1">
                                <div style="margin-bottom: 0.75rem;">
                                    <label id="userNameLabel">Username</label>
                                    <smart-input id="userNameInput" class="w-100" placeholder="Username"></smart-input>
                                </div>

                                <div style="margin-bottom: 1rem;">
                                    <label id="biographyLabel">Biography</label>
                                    <smart-text-area id="biographyInput" class="w-100"
                                        placeholder="Share something here...">
                                    </smart-text-area>
                                </div>

                                <smart-button class="primary">Save changes</smart-button>
                            </div>

                            <div class="custom-col col-entity-md-4 order-1 order-md-2 text-center">
                                <div class="avatar-holder">
                                    <div class="img-as-background square rounded-circle">
                                        <img src="assets/images/phonebook/mark.png" />
                                    </div>
                                </div>

                                <div class="upload-btn-wrapper">
                                    <smart-button id="uploadButton" class="small-button primary"><span
                                            class="material-icons">cloud_upload</span> Upload</smart-button>
                                </div>

                                <small>Choose an image no <br />larger than 3MB</small>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="custom-card">
                    <div class="card-header">
                        <h4 class="label">Private info</h4>
                        <div class="settings-button" #privateInfoButton (click)="toggleMenu(privateInfoButton)"
                        (pointerup)="stopPropagation($event)">…</div>
                    </div>

                    <div class="card-body">
                        <div id="privateInfoContainer">
                            <div class="custom-row">
                                <div class="custom-col col-entity-sm-6">
                                    <label id="firstNameLabel">First name</label>
                                    <smart-input id="firstNameInput" class="w-100" placeholder="First name">
                                    </smart-input>
                                </div>
                                <div class="custom-col col-entity-sm-6">
                                    <label id="lastNameLabel">Last name</label>
                                    <smart-input id="lastNameInput" class="w-100" placeholder="Last name"></smart-input>
                                </div>
                                <div class="custom-col col-entity-sm-12">
                                    <label id="emailLabel">Email</label>
                                    <smart-input id="emailInput" class="w-100" placeholder="Email"></smart-input>
                                </div>
                                <div class="custom-col col-entity-sm-12">
                                    <label id="addressLabel">Address</label>
                                    <smart-input id="addressInput" class="w-100" placeholder="9581 Lovers Ln">
                                    </smart-input>
                                </div>
                                <div class="custom-col col-entity-sm-12">
                                    <label id="address2Label">Address 2</label>
                                    <smart-input id="address2Input" class="w-100" placeholder="7118 Spring St">
                                    </smart-input>
                                </div>
                                <div class="custom-col col-entity-sm-4">
                                    <label id="cityLabel">City</label>
                                    <smart-input id="cityInput" class="w-100"></smart-input>
                                </div>
                                <div class="custom-col col-entity-sm-4">
                                    <label id="stateLabel">State</label>
                                    <smart-input id="stateInput" class="w-100" placeholder="Select a state..."
                                        drop-down-button-position="right"
                                        data-source='["Andhra Pradesh", "Manipur", "Tamil Nadu"]'></smart-input>
                                </div>
                                <div class="custom-col col-entity-sm-4">
                                    <label id="zipLabel">ZIP</label>
                                    <smart-input id="zipInput" class="w-100"></smart-input>
                                </div>
                            </div>

                            <smart-button class="primary">Save changes</smart-button>
                        </div>
                    </div>
                </div>
            </div>
            <div #passwordTemplate id="passwordTemplate">
                <div class="custom-card">
                    <div class="card-header">
                        <h4 class="label">Password</h4>
                    </div>
                    <div class="card-body">
                        <div id="passwordInfoContainer">
                            <div class="current-pass">
                                <label>Current password</label>
                                <smart-input class="w-100"></smart-input>
                                <a href="#" class="styled forgot">Forgot your password?</a>
                            </div>

                            <div class="new-pass">
                                <label>New password</label>
                                <smart-input class="w-100"></smart-input>
                            </div>

                            <div class="re-pass">
                                <label>Verify password</label>
                                <smart-input class="w-100"></smart-input>
                            </div>

                            <smart-button class="primary">Save changes</smart-button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

// templates/admin-template-react/src/Pages/Profile/AccountSettings/AccountSettings.js
import './AccountSettings.scss';
import { useEffect } from 'react';

import { AnimatePresence } from 'framer-motion';

import withAnimation from '../../../hoc/withAnimation';

import { ListBox, ListItem, Button, Input, MultilineTextBox } from '../../../smartImports';

import { defaultTitle } from '../../../contexts/themeContext';
import { useState } from 'react';

const AccountSection = withAnimation(({ openTodayMenu }) => (
    <>
        <div className="card mb-5">
            <div className="card-header">
                <h4 className="label">Public info</h4>
                <div
                    className="settings-button"
                    onClick={(e) => openTodayMenu(e)}
                    onPointerUp={(e) => e.stopPropagation()}
                >…</div>
            </div>

            <div className="card-body">
                <div id="publicInfoContainer" className="row d-flex">
                    <div className="col-md-8 order-2 order-md-1">
                        <div className="mb-3">
                            <label id="userNameLabel">Username</label>
                            <Input id="userNameInput" className="w-100" placeholder="Username"></Input>
                        </div>

                        <div className="mb-4">
                            <label id="biographyLabel">Biography</label>
                            <MultilineTextBox id="biographyInput" className="w-100" placeholder="Share something here..."></MultilineTextBox>
                        </div>

                        <Button className="primary">Save changes</Button>
                    </div>

                    <div className="col-md-4 order-1 order-md-2 text-center">
                        <div className="avatar-holder mb-3">
                            <div className="img-as-background w-80px square rounded-circle mx-auto">
                                <img src="assets/images/phonebook/mark.png" alt='' />
                            </div>
                        </div>

                        <div className="mb-3">
                            <Button id="uploadButton" className="small-button primary"><span className="material-icons">cloud_upload</span> Upload</Button>
                        </div>

                        <small>Choose an image no <br />larger than 3MB</small>
                    </div>
                </div>
            </div>
        </div>

        <div className="card mb-5">
            <div className="card-header">
                <h4 className="label">Private info</h4>
                <div
                    className="settings-button"
                    onClick={(e) => openTodayMenu(e)}
                    onPointerUp={(e) => e.stopPropagation()}
                >…</div>
            </div>

            <div className="card-body">
                <div id="privateInfoContainer">
                    <div className="row mb-3">
                        <div className="mb-3 col-sm-6">
                            <label id="firstNameLabel">First name</label>
                            <Input id="firstNameInput" className="w-100" placeholder="First name"></Input>
                        </div>
                        <div className="mb-3 col-sm-6">
                            <label id="lastNameLabel">Last name</label>
                            <Input id="lastNameInput" className="w-100" placeholder="Last name"></Input>
                        </div>
                        <div className="mb-3 col-sm-12">
                            <label id="emailLabel">Email</label>
                            <Input id="emailInput" className="w-100" placeholder="Email"></Input>
                        </div>
                        <div className="mb-3 col-sm-12">
                            <label id="addressLabel">Address</label>
                            <Input id="addressInput" className="w-100" placeholder="9581 Lovers Ln"></Input>
                        </div>
                        <div className="mb-3 col-sm-12">
                            <label id="address2Label">Address 2</label>
                            <Input id="address2Input" className="w-100" placeholder="7118 Spring St"></Input>
                        </div>
                        <div className="mb-3 col-sm-4">
                            <label id="cityLabel">City</label>
                            <Input id="cityInput" className="w-100"></Input>
                        </div>
                        <div className="mb-3 col-sm-4">
                            <label id="stateLabel">State</label>
                            <Input id="stateInput" className="w-100" placeholder="Select a state..." drop-down-button-position="right" data-source='["Andhra Pradesh", "Manipur", "Tamil Nadu"]'></Input>
                        </div>
                        <div className="mb-3 col-sm-4">
                            <label id="zipLabel">ZIP</label>
                            <Input id="zipInput" className="w-100"></Input>
                        </div>
                    </div>

                    <Button className="primary">Save changes</Button>
                </div>
            </div>
        </div>
    </>
))

const PasswordSection = withAnimation(() => (
    <>
        <div className="card mb-5">
            <div className="card-header">
                <h4 className="label">Password</h4>
            </div>
            <div className="card-body">
                <div id="passwordInfoContainer">
                    <div className="mb-3">
                        <label>Current password</label>
                        <Input className="w-100"></Input>
                        <a href="#" className="styled forgot">Forgot your password?</a>
                    </div>

                    <div className="mb-3">
                        <label>New password</label>
                        <Input className="w-100"></Input>
                    </div>

                    <div className="mb-5">
                        <label>Verify password</label>
                        <Input className="w-100"></Input>
                    </div>

                    <Button className="primary">Save changes</Button>
                </div>
            </div>
        </div>
    </>
))

function AccountSettings({ openTodayMenu }) {

    const [selectedListItem, setSelectedListItem] = useState(0);

    useEffect(() => { document.title = `Settings - ${defaultTitle}` }, []);

    const handleListboxChange = (e) => {

        setSelectedListItem(e.detail.index);

    }

    return (
        <div className="container account-settings">
            <div className="row">
                <div className="col-12 mb-3"><h4>Settings</h4></div>
            </div>

            <div className="row account-settings">
                <div className="col-lg-4 mb-5">
                    <div className="card">
                        <div className="card-header">
                            <h4 className="label">Profile Settings</h4>
                        </div>

                        <div className="card-body">
                            <ListBox onChange={handleListboxChange} id="settingsListBox">
                                <ListItem selected>Account</ListItem>
                                <ListItem>Password</ListItem>
                                <ListItem>Privacy and safety</ListItem>
                                <ListItem>Email notifications</ListItem>
                                <ListItem>Web notifications</ListItem>
                                <ListItem>Widgets</ListItem>
                                <ListItem>Your data</ListItem>
                                <ListItem>Delete account</ListItem>
                            </ListBox>
                        </div>
                    </div>
                </div>

                <div id="mainCol" className="col-lg-8 mb-5">
                    <AnimatePresence mode="wait">
                        {
                            selectedListItem === 0
                                ? <AccountSection key='accountSection' openTodayMenu={openTodayMenu} />
                                : <PasswordSection key='passwordSection' />
                        }
                    </AnimatePresence>
                </div>
            </div>
        </div>
    )
}

export default withAnimation(AccountSettings)
