// templates/admin-template-react/src/Pages/UIElements/General/General.js
import './General.scss';
import { useEffect } from 'react';

import withAnimation from '../../../hoc/withAnimation';
import {
    Accordion, AccordionItem, Button, Pager, Tooltip, ListBox, ListItem, ListItemsGroup
    , ProgressBar, CircularProgressBar, Breadcrumb
} from '../../../smartImports';

import { defaultTitle } from '../../../contexts/themeContext';

function General() {

    useEffect(() => { document.title = `General - ${defaultTitle}` }, []);

    return (
        <div className="container general-page">
            <div className="row">
                <div className="col-12 mb-3"><h4>General-Use Components</h4></div>
            </div>

            <div className="row">
                <div className="col-lg-6">
                    <div className="card mb-5">
                        <div className="card-header">
                            <h4 className="label">Accordion</h4>
                        </div>

                        <div className="card-body">
                            <Accordion className="w-100">
                                <AccordionItem label="First Item">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque aliquam at nunc sed aliquet. Quisque nec tristique lacus, sit amet venenatis risus. Pellentesque nisl odio, scelerisque nec ipsum ut, ullamcorper fringilla odio. Interdum et malesuada fames ac ante ipsum primis in faucibus.</AccordionItem>
                                <AccordionItem label="Second Item">Proin eu fringilla ante. Fusce tempus est at dui posuere blandit. Pellentesque id eros dui.</AccordionItem>
                                <AccordionItem label="Third Item">Duis ut nunc non eros rutrum laoreet commodo nec nulla. Duis volutpat dapibus mi in interdum. Praesent ornare ex metus.</AccordionItem>
                                <AccordionItem label="Fourth Item">Vestibulum in leo porta, tempus orci eleifend, pharetra libero.</AccordionItem>
                            </Accordion>
                        </div>
                    </div>

                    <div className="card mb-5">
                        <div className="card-header">
                            <h4 className="label">Breadcrumbs</h4>
                        </div>
                        <div className="card-body">
                            <Breadcrumb
                                className="w-100 mb-5"
                                dataSource={[{ "label": "<a href='#home'>Home</a>", "value": "home" }, { "label": "<a href='#catalog'>Catalog</a>", "value": "catalog" }, { "label": "<a href='#apple_computers'>Apple Computers</a>", "value": "apple_computers" }, { "label": "Macbook Pro 13", "value": "macbook_pro_13" }]}></Breadcrumb>
                        </div>
                    </div>

                    <div className="card mb-5">
                        <div className="card-header">
                            <h4 className="label">Progressbars</h4>
                        </div>
                        <div className="card-body">
                            <ProgressBar className="w-100 mb-5" value={30}></ProgressBar>
                            <ProgressBar className="w-100 mb-5 barber-shop-effect" value={50}></ProgressBar>
                            <ProgressBar className="w-100 mb-5 barber-shop-effect" indeterminate></ProgressBar>
                            <div className="d-flex justify-content-between">
                                <CircularProgressBar className="w-150 h-150" value={50}></CircularProgressBar>
                                <CircularProgressBar className="w-150 h-150 barber-shop-effect" indeterminate></CircularProgressBar>
                            </div>
                        </div>
                    </div>
                </div>

                <div className="col-lg-6">
                    <div className="card mb-5">
                        <div className="card-header">
                            <h4 className="label">Badges</h4>
                        </div>
                        <div className="card-body">
                            <div className="mb-5">
                                <span className="smart-badge smart-badge-light">Light</span>&nbsp;<span className="smart-badge smart-badge-dark">Dark</span>&nbsp;<span className="smart-badge smart-badge-info">Info</span>&nbsp;<span className="smart-badge smart-badge-success">Success</span>&nbsp;<span className="smart-badge smart-badge-warning">Warning</span>&nbsp;<span className="smart-badge smart-badge-danger">Danger</span>
                            </div>

                            <div>
                                <span className="smart-badge smart-badge-light smart-badge-pill">Light</span>&nbsp;<span className="smart-badge smart-badge-dark smart-badge-pill">Dark</span>&nbsp;<span className="smart-badge smart-badge-info smart-badge-pill">Info</span>&nbsp;<span className="smart-badge smart-badge-success smart-badge-pill">Success</span>&nbsp;<span className="smart-badge smart-badge-warning smart-badge-pill">Warning</span>&nbsp;<span className="smart-badge smart-badge-danger smart-badge-pill">Danger</span>
                            </div>
                        </div>
                    </div>

                    <div className="card mb-5">
                        <div className="card-header">
                            <h4 className="label">List Boxes</h4>
                        </div>
                        <div className="card-body">
                            <div className="row d-flex">
                                <div className="col-6 mb-5">
                                    <h6>With selection</h6>
                                    <ListBox className="h-auto">
                                        <ListItem>Item 1</ListItem>
                                        <ListItem selected>Item 2</ListItem>
                                        <ListItem>Item 3</ListItem>
                                    </ListBox>
                                </div>
                                <div className="col-6 mb-5">
                                    <h6>No selection</h6>
                                    <ListBox className="h-auto" selection-mode="none">
                                        <ListItem>Item 1</ListItem>
                                        <ListItem>Item 2</ListItem>
                                        <ListItem>Item 3</ListItem>
                                    </ListBox>
                                </div>
                                <div className="col-6 mb-5">
                                    <h6>Disabled item</h6>
                                    <ListBox className="h-auto">
                                        <ListItem disabled>Item 1</ListItem>
                                        <ListItem selected>Item 2</ListItem>
                                        <ListItem>Item 3</ListItem>
                                    </ListBox>
                                </div>
                                <div className="col-6 mb-5">
                                    <h6>With grouping</h6>
                                    <ListBox className="h-auto">
                                        <ListItemsGroup label="Group 1">
                                            <ListItem>Item 1</ListItem>
                                        </ListItemsGroup>
                                        <ListItemsGroup label="Group 2">
                                            <ListItem selected>Item 2</ListItem>
                                            <ListItem>Item 3</ListItem>
                                        </ListItemsGroup>
                                    </ListBox>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div className="card mb-5">
                        <div className="card-header">
                            <h4 className="label">Pagers</h4>
                        </div>
                        <div className="card-body" id="pagersContainer">
                            <Pager
                                className="mb-5"
                                showPrevNextNavigationButtons
                                autoEllipsis="both"
                                showPageIndexSelectors
                                pagesCount={20}
                                pageIndexSelectors={10}
                            >
                            </Pager>
                            <Pager
                                className="mb-5"
                                showNavigationButtonLabels
                                showPrevNextNavigationButtons
                                showFirstLastNavigationButtons
                                showPageIndexSelectors
                                pagesCount={5}
                                pageIndexSelectors={5}
                                style={{ fontFamily: "inherit !important" }}
                            ></Pager>
                            <Pager
                                className="w-100"
                                showPageSizeSelector
                                showNavigationInput
                                showPrevNextNavigationButtons
                                pagesCount={10}
                                showSummary
                            ></Pager>
                        </div>
                    </div>

                    <div className="card mb-5">
                        <div className="card-header">
                            <h4 className="label">Tooltips</h4>
                        </div>
                        <div className="card-body">
                            <Button id="buttonWithTooltip1" className="small-button success">Tooltip on left</Button>&nbsp;<Button id="buttonWithTooltip2" className="small-button">Tooltip on top</Button>&nbsp;<Button id="buttonWithTooltip3" className="small-button secondary">Tooltip on bottom</Button>&nbsp;<Button id="buttonWithTooltip4" className="small-button primary">Tooltip on right</Button>
                            <Tooltip selector="buttonWithTooltip1" arrow position="left">Tooltip on left</Tooltip>
                            <Tooltip selector="buttonWithTooltip2" arrow position="top">Tooltip on top</Tooltip>
                            <Tooltip selector="buttonWithTooltip3" arrow position="bottom">Tooltip on bottom</Tooltip>
                            <Tooltip selector="buttonWithTooltip4" arrow position="right">Tooltip on right</Tooltip>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default withAnimation(General)

// templates/admin-template-angular/src/app/pages/ui-elements/general/general.component.ts
import { AfterViewInit, Component, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'sm-general',
  templateUrl: './general.component.html',
  styleUrls: ['./general.component.scss'],
  encapsulation: ViewEncapsulation.None
})
export class GeneralComponent implements AfterViewInit {

  constructor() { }

  ngAfterViewInit(): void {

    setTimeout(() => {
      const breadcrumbItems = document.querySelectorAll('.general-breadcrumb-item');

      breadcrumbItems.forEach(item => {

        const path = `#${item.textContent?.replace(' ', '_')?.toLocaleLowerCase()}`;

        item.addEventListener('click', (e) => {
          e.preventDefault();

          const hashtagIndex = window.location.href.indexOf('#');

          if (hashtagIndex === -1) {

            window.location.href += path;

          } else {
            
            const basePath = window.location.href.substring(0, hashtagIndex);
            window.location.href = `${basePath}${path}`;

          }
        })

      })

    }, 1000) //Workaround, because after view init the breadcrumbs are not initialized

  }

}

<div class="container general">
    <div class="custom-row">
        <div class="general-header custom-col">
            <h4>General-Use Components</h4>
        </div>
    </div>

    <div class="custom-row">
        <div class="general-entity custom-col">
            <div class="custom-card">
                <div class="card-header">
                    <h4 class="label">Accordion</h4>
                </div>

                <div class="card-body">
                    <smart-accordion>
                        <smart-accordion-item label="First Item">Lorem ipsum dolor sit amet, consectetur adipiscing
                            elit. Pellentesque aliquam at nunc sed aliquet. Quisque nec tristique lacus, sit amet
                            venenatis risus. Pellentesque nisl odio, scelerisque nec ipsum ut, ullamcorper fringilla
                            odio. Interdum et malesuada fames ac ante ipsum primis in faucibus.</smart-accordion-item>
                        <smart-accordion-item label="Second Item">Proin eu fringilla ante. Fusce tempus est at dui
                            posuere blandit. Pellentesque id eros dui.</smart-accordion-item>
                        <smart-accordion-item label="Third Item">Duis ut nunc non eros rutrum laoreet commodo nec nulla.
                            Duis volutpat dapibus mi in interdum. Praesent ornare ex metus.</smart-accordion-item>
                        <smart-accordion-item label="Fourth Item">Vestibulum in leo porta, tempus orci eleifend,
                            pharetra libero.</smart-accordion-item>
                    </smart-accordion>
                </div>
            </div>

            <div class="custom-card">
                <div class="card-header">
                    <h4 class="label">Breadcrumbs</h4>
                </div>
                <div class="card-body">
                    <smart-breadcrumb
                        data-source='[{ "label": "
                        <a class="general-breadcrumb-item">Home</a>", "value": "home" }, { "label": "<a class="general-breadcrumb-item">Catalog</a>", "value": "catalog" }, { "label": "<a class="general-breadcrumb-item">Apple Computers</a>", "value": "apple_computers" }, { "label": "Macbook Pro 13", "value": "macbook_pro_13" }'>
                    </smart-breadcrumb>
                </div>
            </div>

            <div class="custom-card">
                <div class="card-header">
                    <h4 class="label">Progressbars</h4>
                </div>
                <div class="card-body">
                    <smart-progress-bar [value]="30"></smart-progress-bar>
                    <smart-progress-bar class="barber-shop-effect" [value]="50"></smart-progress-bar>
                    <smart-progress-bar class="barber-shop-effect" [indeterminate]="true">
                    </smart-progress-bar>
                    <div class="general-circular-progress-wrapper">
                        <smart-circular-progress-bar [value]="50"></smart-circular-progress-bar>
                        <smart-circular-progress-bar class="barber-shop-effect" [indeterminate]="true">
                        </smart-circular-progress-bar>
                    </div>
                </div>
            </div>
        </div>
        <div class="general-entity custom-col">
            <div class="custom-card">
                <div class="card-header">
                    <h4 class="label">Badges</h4>
                </div>
                <div class="card-body">
                    <div class="general-upper-badges-wrapper">
                        <span class="smart-badge smart-badge-light">Light</span>&nbsp;<span
                            class="smart-badge smart-badge-dark">Dark</span>&nbsp;<span
                            class="smart-badge smart-badge-info">Info</span>&nbsp;<span
                            class="smart-badge smart-badge-success">Success</span>&nbsp;<span
                            class="smart-badge smart-badge-warning">Warning</span>&nbsp;<span
                            class="smart-badge smart-badge-danger">Danger</span>
                    </div>

                    <div>
                        <span class="smart-badge smart-badge-light smart-badge-pill">Light</span>&nbsp;<span
                            class="smart-badge smart-badge-dark smart-badge-pill">Dark</span>&nbsp;<span
                            class="smart-badge smart-badge-info smart-badge-pill">Info</span>&nbsp;<span
                            class="smart-badge smart-badge-success smart-badge-pill">Success</span>&nbsp;<span
                            class="smart-badge smart-badge-warning smart-badge-pill">Warning</span>&nbsp;<span
                            class="smart-badge smart-badge-danger smart-badge-pill">Danger</span>
                    </div>
                </div>
            </div>

            <div class="custom-card">
                <div class="card-header">
                    <h4 class="label">List Boxes</h4>
                </div>
                <div class="card-body">
                    <div class="general-listboxes-wrapper">
                        <div class="general-listbox">
                            <h6>With selection</h6>
                            <smart-list-box class="h-auto">
                                <smart-list-item>Item 1</smart-list-item>
                                <smart-list-item [selected]="true">Item 2</smart-list-item>
                                <smart-list-item>Item 3</smart-list-item>
                            </smart-list-box>
                        </div>
                        <div class="general-listbox">
                            <h6>No selection</h6>
                            <smart-list-box class="h-auto" selection-mode="none">
                                <smart-list-item>Item 1</smart-list-item>
                                <smart-list-item>Item 2</smart-list-item>
                                <smart-list-item>Item 3</smart-list-item>
                            </smart-list-box>
                        </div>
                        <div class="general-listbox">
                            <h6>Disabled item</h6>
                            <smart-list-box class="h-auto">
                                <smart-list-item disabled>Item 1</smart-list-item>
                                <smart-list-item [selected]="true">Item 2</smart-list-item>
                                <smart-list-item>Item 3</smart-list-item>
                            </smart-list-box>
                        </div>
                        <div class="general-listbox">
                            <h6>With grouping</h6>
                            <smart-list-box class="h-auto">
                                <smart-list-items-group label="Group 1">
                                    <smart-list-item>Item 1</smart-list-item>
                                </smart-list-items-group>
                                <smart-list-items-group label="Group 2">
                                    <smart-list-item [selected]="true">Item 2</smart-list-item>
                                    <smart-list-item>Item 3</smart-list-item>
                                </smart-list-items-group>
                            </smart-list-box>
                        </div>
                    </div>
                </div>
            </div>

            <div class="custom-card">
                <div class="card-header">
                    <h4 class="label">Pagers</h4>
                </div>
                <div class="card-body general-pagers-wrapper">
                    <smart-pager class="mb-5" [showPrevNextNavigationButtons]="true" [autoEllipsis]="'both'"
                        [showPageIndexSelectors]="true" [pagesCount]="20" [pageIndexSelectors]="10"></smart-pager>
                    <smart-pager class="mb-5" [showNavigationButtonLabels]="true" [showPrevNextNavigationButtons]="true"
                        [showFirstLastNavigationButtons]="true" [showPageIndexSelectors]="true" [pagesCount]="5"
                        [pageIndexSelectors]="5"></smart-pager>
                    <smart-pager class="w-100" [showPageSizeSelector]="true" [showNavigationInput]="true"
                        [showPrevNextNavigationButtons]="true" [pagesCount]="10" [showSummary]="true"></smart-pager>
                </div>
            </div>

            <div class="custom-card">
                <div class="card-header">
                    <h4 class="label">Tooltips</h4>
                </div>
                <div class="card-body">
                    <smart-button id="buttonWithTooltip1" class="small-button success">Tooltip on left</smart-button>
                    <smart-tooltip selector="buttonWithTooltip1" [arrow]="true" [position]="'left'">Tooltip on left
                    </smart-tooltip>&nbsp;<smart-button id="buttonWithTooltip2" class="small-button">Tooltip on top
                    </smart-button>
                    <smart-tooltip selector="buttonWithTooltip2" [arrow]="true" [position]="'top'">Tooltip on top
                    </smart-tooltip>&nbsp;<smart-button id="buttonWithTooltip3" class="small-button secondary">Tooltip
                        on bottom
                    </smart-button>
                    <smart-tooltip selector="buttonWithTooltip3" [arrow]="true" [position]="'bottom'">Tooltip on bottom
                    </smart-tooltip>&nbsp;<smart-button id="buttonWithTooltip4" class="small-button primary">Tooltip on
                        right</smart-button>
                    <smart-tooltip selector="buttonWithTooltip4" [arrow]="true" [position]="'right'">Tooltip on right
                    </smart-tooltip>
                </div>
            </div>
        </div>
    </div>
</div>
