// templates/admin-template-react/src/Components/Core/Sidebar/Sidebar.js
import { useState, forwardRef, useEffect, useRef, useCallback } from 'react'

import { ReactComponent as SidebarToggleSVG } from '../../../assets/images/sidebar-toggle.svg'

import { useSidbarContext } from '../../../contexts/sidebarContext';

import { Tree, TreeItem, TreeItemsGroup, Tooltip } from '../../../smartImports';

import { useNavigate, Link, useLocation } from 'react-router-dom'

const Sidebar = forwardRef(({ primaryContainerRef, toggleCollapsedSidebarRef }, ref) => {

    let navigate = useNavigate();
    const location = useLocation();

    const { sidebarState, setSidebarState } = useSidbarContext();

    const [containsHoverOnToggleClass, setContainsHoverOnToggleClass] = useState(false);

    const treeRef = useRef(null);

    const generateBreadcrumb = () => {

        const breadcrumbGroups = document.body.querySelectorAll("#tree .smart-tree-items-group[expanded]");
        let breadcrumbGroupsHTML = '';

        if (breadcrumbGroups) {

            breadcrumbGroups.forEach(breadcrumbGroupName => {

                let group = breadcrumbGroupName
                    .querySelector(".smart-tree-item-label-container .smart-tree-item-label-element")
                    .cloneNode(true);

                if (group.querySelector('.material-icons')) {
                    group.querySelector('.material-icons').remove();
                }

                breadcrumbGroupsHTML +=
                    '<li class="breadcrumb-item"><a href="javascript:;" class="text-muted">'
                    + group.textContent.trim()
                    + '</a></li>';

            });

        }

        let breadcrumbItem = document.body
            .querySelector("#tree .smart-tree-item[selected] > .smart-tree-item-label-container .smart-tree-item-label-element a");

        let breadcrumbItemName = breadcrumbItem?.textContent;
        let breadcrumbItemHref = document.body
            .querySelector("#tree .smart-tree-item[selected] > .smart-tree-item-label-container .smart-tree-item-label-element a")
            ?.getAttribute('href');

        if (breadcrumbItemName && breadcrumbItemHref) {

            document.body.querySelector("#breadcrumb-title").innerHTML = breadcrumbItemName;
            breadcrumbGroupsHTML +=
                '<li class="breadcrumb-item"><a href="'
                + breadcrumbItemHref
                + '" class="text-muted">'
                + breadcrumbItemName
                + '</a></li>';

        }

        if (breadcrumbGroupsHTML) {
            document.body.querySelector("#breadcrumb-list").innerHTML = breadcrumbGroupsHTML;
        }
    }

    const selectTreeItem = useCallback(() => {

        const smartItem = document.querySelector(`#tree smart-tree-item a[href="${location.pathname}"]`)
            .closest('smart-tree-item');

        treeRef.current.select(smartItem);

        treeRef.current.ensureVisible(smartItem);


    }, [location])

    useEffect(() => {

        selectTreeItem();

    }, [location, selectTreeItem])

    useEffect(() => {

        setTimeout(() => generateBreadcrumb(), 900);

    }, []);

    const handleToggleButtonClick = () => {

        setSidebarState({
            collapsed: !sidebarState.collapsed,
            autoCollapsed: false
        })

        if (window.innerWidth >= 992) {

            primaryContainerRef?.current.classList.toggle('collapsed', sidebarState.collapsed);
            toggleCollapsedSidebarRef.current.checked = sidebarState.collapsed;

        }
    }

    const handleTreeChange = () => generateBreadcrumb();

    const handleMouseEnter = () => {

        if (primaryContainerRef?.current.classList.contains('collapsed')) {
            setContainsHoverOnToggleClass(false);
        } else {
            setContainsHoverOnToggleClass(true);
        }

    }

    const handleSelection = (e) => {

        const path = e.srcElement?.querySelector('a')?.getAttribute('href');
        if (path) navigate(path);

    }

    return (
        <>
            <aside
                ref={ref}
                id="sideBar"
                className={`sidebar ${containsHoverOnToggleClass ? "hover-on-toggle" : ""}`}
                onMouseEnter={handleMouseEnter}>
                <div className="logo-holder">
                    <div className="spacer w-auto"></div>
                    <div className="logo">
                        <Link to="/">
                            <img alt='' src="assets/images/logo-htmlelements.svg" />
                        </Link>
                    </div>

                    <div id="toggleButton" className="toggle-button" onClick={handleToggleButtonClick}>
                        <SidebarToggleSVG className='svg' />
                    </div>
                </div>

                <div className="tree-holder">
                    <Tree
                        ref={treeRef}
                        id="tree"
                        expandMode='single'
                        selectionMode="one"
                        selectionTarget="leaf"
                        toggleElementPosition="far"
                        toggleMode="click"
                        onChange={handleTreeChange}
                    >
                        <TreeItem onClick={handleSelection}>
                            <span className="material-icons">layers</span>
                            <a href="/">
                                <span className="label-name">Dashboard</span>
                            </a>
                        </TreeItem>

                        <TreeItem id="pagesLabel" label="pagesTemplate" className="group-label smart-element smart-tree-item smart-unselectable"></TreeItem>
                        <TreeItemsGroup>
                            <span className="material-icons">dashboard</span>
                            <span className="label-name">Applications</span>

                            <TreeItemsGroup>Dashboards
                                <TreeItem onClick={handleSelection}><a href="/dashboard-1">Dashboard 1</a></TreeItem>
                                <TreeItem onClick={handleSelection}><a href="/dashboard-2">Dashboard 2</a></TreeItem>
                                <TreeItem onClick={handleSelection}>
                                    <a href="/dashboard-3">Dashboard 3</a>
                                    <span className="smart-badge smart-badge-danger">New</span>
                                </TreeItem>
                            </TreeItemsGroup>

                            <TreeItemsGroup>E-commerce
                                <TreeItem onClick={handleSelection}><a href="/e-commerce">Dashboard</a></TreeItem>
                                <TreeItem onClick={handleSelection}><a href="/clients">Clients</a></TreeItem>
                                <TreeItem onClick={handleSelection}>
                                    <a href="/e-commerce-details">Details</a>
                                    <span className="smart-badge smart-badge-danger">New</span>
                                </TreeItem>
                                <TreeItem onClick={handleSelection}>
                                    <a href="/e-commerce-list">List</a>
                                    <span className="smart-badge smart-badge-danger">New</span>
                                </TreeItem>
                                <TreeItem onClick={handleSelection}>
                                    <a href="/e-commerce-checkout">Checkout</a>
                                    <span className="smart-badge smart-badge-danger">New</span>
                                </TreeItem>
                            </TreeItemsGroup>

                            <TreeItemsGroup>Analytics
                                <TreeItem onClick={handleSelection}><a href="/analytics">Dashboard</a></TreeItem>
                            </TreeItemsGroup>

                            <TreeItemsGroup>Projects
                                <TreeItem onClick={handleSelection}><a href="/projects-list-1">List 1</a></TreeItem>
                                <TreeItem onClick={handleSelection}>
                                    <a href="/projects-list-2">List 2</a>
                                    <span className="smart-badge smart-badge-danger">New</span>
                                </TreeItem>
                                <TreeItem onClick={handleSelection}><a href="/detail">Detail</a></TreeItem>
                            </TreeItemsGroup>

                            <TreeItemsGroup>Crypto
                                <TreeItem onClick={handleSelection}><a href="/crypto">Dashboard</a></TreeItem>
                            </TreeItemsGroup>

                            <TreeItemsGroup>Profile
                                <TreeItem onClick={handleSelection}><a href="/profile-1">Overview 1</a></TreeItem>
                                <TreeItem onClick={handleSelection}>
                                    <a href="/profile-2">Overview 2</a>
                                    <span className="smart-badge smart-badge-danger">New</span>
                                </TreeItem>
                                <TreeItem onClick={handleSelection}>
                                    <a href="/users-list">Users</a>
                                    <span className="smart-badge smart-badge-danger">New</span>
                                </TreeItem>
                                <TreeItem onClick={handleSelection}>
                                    <a href="/social">Social Page</a></TreeItem>
                                <TreeItem onClick={handleSelection}>
                                    <a href="/settings">Account Settings</a></TreeItem>
                            </TreeItemsGroup>

                            <TreeItemsGroup>Kanban
                                <TreeItem onClick={handleSelection}><a href="/tasks">Tasks 1</a></TreeItem>
                                <TreeItem onClick={handleSelection}>
                                    <a href="/tasks-2">Tasks 2</a>
                                    <span className="smart-badge smart-badge-danger">New</span>
                                </TreeItem>
                            </TreeItemsGroup>

                            <TreeItem onClick={handleSelection}><a href="/chat">Chat</a></TreeItem>
                            <TreeItem onClick={handleSelection}>
                                <a href="/inbox">Inbox</a>
                                <span className="smart-badge smart-badge-danger">New</span>
                            </TreeItem>
                        </TreeItemsGroup>

                        <TreeItemsGroup>
                            <span className="material-icons">contact_page</span>
                            <span className="label-name">Pages</span>

                            <TreeItem onClick={handleSelection}><a href="/sign-in">Sign In</a></TreeItem>
                            <TreeItem onClick={handleSelection}><a href="/sign-up">Sign Up</a></TreeItem>
                            <TreeItem onClick={handleSelection}><a href="/reset-password">Reset Password</a></TreeItem>

                            <TreeItem onClick={handleSelection}><a href="/invoice">Invoice</a></TreeItem>
                            <TreeItem onClick={handleSelection}><a href="/pricing">Pricing</a></TreeItem>

                            <TreeItem onClick={handleSelection}><a href="/404">404 Page</a></TreeItem>
                            <TreeItem onClick={handleSelection}><a href="/500">500 Page</a></TreeItem>

                            <TreeItem onClick={handleSelection}>
                                <a href="/knowledge-base">Knowledge Base</a>
                                <span className="smart-badge smart-badge-danger">New</span>
                            </TreeItem>

                            <TreeItem onClick={handleSelection}><a href="/blank">Blank Page</a></TreeItem>
                        </TreeItemsGroup>

                        <TreeItemsGroup>
                            <span className="material-icons">library_books</span>
                            <span className="label-name">Documentation</span>

                            <TreeItem onClick={handleSelection}><a href="/introduction">Introduction</a></TreeItem>
                            <TreeItem onClick={handleSelection}><a href="/getting-started">Getting Started</a></TreeItem>
                            <TreeItem onClick={handleSelection}><a href="/plugins">Plugins</a></TreeItem>
                            <TreeItem onClick={handleSelection}><a href="/changelog">Changelog</a></TreeItem>
                        </TreeItemsGroup>

                        <TreeItem id="toolsLabel" label="toolsTemplate" className="group-label smart-element smart-tree-item smart-unselectable"></TreeItem>

                        <TreeItemsGroup>
                            <span className="material-icons">grid_on</span>
                            <span className="label-name">UI Elements</span>

                            <TreeItem onClick={handleSelection}><a href="/toasts">Toasts</a></TreeItem>
                            <TreeItem onClick={handleSelection}><a href="/buttons">Buttons</a></TreeItem>
                            <TreeItem onClick={handleSelection}><a href="/cards">Cards</a></TreeItem>
                            <TreeItem onClick={handleSelection}><a href="/carousel">Carousel</a></TreeItem>
                            <TreeItem onClick={handleSelection}><a href="/embed-video">Embed Video</a></TreeItem>
                            <TreeItem onClick={handleSelection}><a href="/general">General</a></TreeItem>
                            <TreeItem onClick={handleSelection}><a href="/grid-layout">Grid Layout</a></TreeItem>
                            <TreeItem onClick={handleSelection}><a href="/modals">Modals</a></TreeItem>
                            <TreeItem onClick={handleSelection}><a href="/tabs">Tabs</a></TreeItem>
                            <TreeItem onClick={handleSelection}><a href="/typography">Typography</a></TreeItem>
                        </TreeItemsGroup>

                        <TreeItemsGroup>
                            <span className="material-icons">favorite</span>
                            <span className="label-name">Icons</span>

                            <TreeItem onClick={handleSelection}><a href="/feather">Feather</a></TreeItem>
                            <TreeItem onClick={handleSelection}><a href="/font-awesome">Font Awesome</a></TreeItem>
                        </TreeItemsGroup>

                        <TreeItemsGroup>
                            <span className="material-icons">fact_check</span>
                            <span className="label-name">Forms</span>
                            <TreeItem onClick={handleSelection}><a href="/layouts">Layouts</a></TreeItem>
                            <TreeItem onClick={handleSelection}><a href="/basic-inputs">Basic Inputs</a></TreeItem>
                            <TreeItem onClick={handleSelection}><a href="/input-groups">Input Groups</a></TreeItem>
                        </TreeItemsGroup>

                        <TreeItem onClick={handleSelection}>
                            <span className="material-icons">table_chart</span>
                            <a href="/tables">
                                <span className="label-name">Tables</span>
                            </a>
                        </TreeItem>

                        <TreeItem id="pluginLabel" label="pluginTemplate" className="group-label smart-element smart-tree-item smart-unselectable"></TreeItem>

                        <TreeItemsGroup>
                            <span className="material-icons">fact_check</span>
                            <span className="label-name">Form Plugins</span>

                            <TreeItem onClick={handleSelection}><a href="/advanced-inputs">Advanced Inputs</a></TreeItem>
                            <TreeItem onClick={handleSelection}><a href="/editor">Editor</a></TreeItem>
                            <TreeItem onClick={handleSelection}><a href="/validation">Validation</a></TreeItem>
                            <TreeItem onClick={handleSelection}><a href="/wizard">Wizard</a></TreeItem>
                        </TreeItemsGroup>

                        <TreeItemsGroup>
                            <span className="material-icons">table_chart</span>
                            <span className="label-name">Data Tables</span>

                            <TreeItem onClick={handleSelection}><a href="/responsive-table">Responsive Table</a></TreeItem>
                            <TreeItem onClick={handleSelection}><a href="/table-with-buttons">Table with Buttons</a></TreeItem>
                            <TreeItem onClick={handleSelection}><a href="/column-search">Column Search</a></TreeItem>
                            <TreeItem onClick={handleSelection}><a href="/multi-selection">Multi Selection</a></TreeItem>
                            <TreeItem onClick={handleSelection}><a href="/ajax-data">Ajax Sourced Data</a></TreeItem>
                        </TreeItemsGroup>

                        <TreeItem onClick={handleSelection}>
                            <span className="material-icons">pie_chart</span>
                            <a href="/charts">
                                <span className="label-name">Charts</span>
                            </a>
                        </TreeItem>

                        <TreeItem onClick={handleSelection}>
                            <span className="material-icons">alarm</span>
                            <a href="/notifications">
                                <span className="label-name">Notifications</span>
                            </a>
                        </TreeItem>

                        <TreeItemsGroup>
                            <span className="material-icons">place</span>
                            <span className="label-name">Maps</span>

                            <TreeItem onClick={handleSelection}><a href="/google-maps">Google Maps</a></TreeItem>
                        </TreeItemsGroup>

                        <TreeItem onClick={handleSelection}>
                            <span className="material-icons">calendar_today</span>
                            <a href="/scheduler">
                                <span className="label-name">Scheduler</span>
                            </a>
                        </TreeItem>

                        <TreeItemsGroup>
                            <span className="material-icons">share</span>
                            <span className="label-name">Multi Level</span>

                            <TreeItemsGroup>Two Levels
                                <TreeItem>Item 1</TreeItem>
                                <TreeItem>Item 2</TreeItem>
                            </TreeItemsGroup>
                            <TreeItemsGroup>Three Levels
                                <TreeItemsGroup>Item 1
                                    <TreeItem>Item 1</TreeItem>
                                    <TreeItem>Item 2</TreeItem>
                                </TreeItemsGroup>
                                <TreeItem>Item 2</TreeItem>
                            </TreeItemsGroup>
                        </TreeItemsGroup>
                    </Tree>
                </div>
            </aside>
            <Tooltip id="usageTooltipNormal" selector="toggleButton" position="right" className="animation">
                <span className="show">Open Sidebar</span>
                <span className="hide">Close Sidebar</span>
            </Tooltip>
        </>
    )
})

export default Sidebar

// templates/admin-template-angular/src/app/core/sidebar/sidebar.component.ts
import { AfterViewInit, Component, EventEmitter, Input, Output, ViewChild, ViewEncapsulation } from '@angular/core';
import { TreeComponent } from 'smart-webcomponents-angular/tree';
import { SidebarToggleOptions } from 'src/app/services/sidebar.service';

@Component({
  selector: 'sm-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.scss'],
  encapsulation: ViewEncapsulation.None
})

export class SidebarComponent implements AfterViewInit {

  @ViewChild('tree', { read: TreeComponent, static: false }) tree!: TreeComponent;
  @Input('isSidebarExpanded') isExpanded!: boolean;
  @Output() onToggle = new EventEmitter<SidebarToggleOptions>();
  @Output() getTreeComponent = new EventEmitter<TreeComponent>();

  ngAfterViewInit(): void {

    this.getTreeComponent.emit(this.tree);
    
  }

  handleMouseEnter($event: Event) {

    const sidebar = ($event.target as HTMLElement);

    if (!sidebar.classList.contains('sidebar-not-expanded')) {

      sidebar.classList.remove('sidebar-toggle-on-hover');

    } else {

      sidebar.classList.add('sidebar-toggle-on-hover');

    }

  }

  toggleSidebar(sidebarElement: HTMLElement): void {

    if (this.isExpanded) {
      sidebarElement.classList.add('sidebar-not-expanded');
    }

    this.onToggle.emit(
      {
        expansionPreference: !this.isExpanded,
        forMobile: window.innerWidth < 767 ? true : false
      });
  }
}

<ng-container>
    <aside id="sideBar" class="sidebar" [class.sidebar-not-expanded]="!isExpanded" #sidebar
        (mouseenter)="handleMouseEnter($event)">
        <div class="logo-holder">
            <div class="logo" [class.hide-logo]="!isExpanded">
                <a routerLink="/">
                    <img src="../../../assets/images/logo-htmlelements.svg" />
                </a>
            </div>
            <div id="toggleButton" class="toggle-button" (click)="toggleSidebar(sidebar)">
                <svg class="sidebar-toggle-svg" xmlns="http://www.w3.org/2000/svg"
                    xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24"
                    version="1.1">
                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                        <polygon points="0 0 24 0 24 24 0 24"></polygon>
                        <path
                            d="M5.29288961,6.70710318 C4.90236532,6.31657888 4.90236532,5.68341391 5.29288961,5.29288961 C5.68341391,4.90236532 6.31657888,4.90236532 6.70710318,5.29288961 L12.7071032,11.2928896 C13.0856821,11.6714686 13.0989277,12.281055 12.7371505,12.675721 L7.23715054,18.675721 C6.86395813,19.08284 6.23139076,19.1103429 5.82427177,18.7371505 C5.41715278,18.3639581 5.38964985,17.7313908 5.76284226,17.3242718 L10.6158586,12.0300721 L5.29288961,6.70710318 Z"
                            fill="#000000" fill-rule="nonzero"
                            transform="translate(8.999997, 11.999999) scale(-1, 1) translate(-8.999997, -11.999999)">
                        </path>
                        <path
                            d="M10.7071009,15.7071068 C10.3165766,16.0976311 9.68341162,16.0976311 9.29288733,15.7071068 C8.90236304,15.3165825 8.90236304,14.6834175 9.29288733,14.2928932 L15.2928873,8.29289322 C15.6714663,7.91431428 16.2810527,7.90106866 16.6757187,8.26284586 L22.6757187,13.7628459 C23.0828377,14.1360383 23.1103407,14.7686056 22.7371482,15.1757246 C22.3639558,15.5828436 21.7313885,15.6103465 21.3242695,15.2371541 L16.0300699,10.3841378 L10.7071009,15.7071068 Z"
                            fill="#000000" fill-rule="nonzero" opacity="0.3"
                            transform="translate(15.999997, 11.999999) scale(-1, 1) rotate(-270.000000) translate(-15.999997, -11.999999)">
                        </path>
                    </g>
                </svg>
            </div>
        </div>

        <div class="tree-holder">
            <smart-tree #tree id="tree" expand-mode="single" selected-indexes='["1.0"]' selection-mode="one"
                selection-target="leaf" toggle-element-position="far" toggle-mode="click">
                <smart-tree-item routerLink="/">
                    <span class="material-icons">layers</span>
                    <a>
                        <span class="label-name">Dashboard</span>
                    </a>
                </smart-tree-item>

                <smart-tree-item id="pagesLabel" label="PAGES" class="group-label"></smart-tree-item>
                <smart-tree-items-group>
                    <span class="material-icons">dashboard</span> <span class="label-name">Applications</span>

                    <smart-tree-items-group>Dashboards
                        <smart-tree-item routerLink="/dashboard-1"><a>Dashboard 1</a></smart-tree-item>
                        <smart-tree-item routerLink="/dashboard-2"><a>Dashboard 2</a></smart-tree-item>
                        <smart-tree-item routerLink="/dashboard-3"><a>Dashboard 3</a> <span
                                class="smart-badge smart-badge-danger">New</span></smart-tree-item>
                    </smart-tree-items-group>

                    <smart-tree-items-group>E-commerce
                        <smart-tree-item routerLink="/e-commerce"><a>Dashboard</a>
                        </smart-tree-item>
                        <smart-tree-item routerLink="/clients"><a>Clients</a></smart-tree-item>
                        <smart-tree-item routerLink="/e-commerce-details"><a>Details</a>
                            <span class="smart-badge smart-badge-danger">New</span></smart-tree-item>
                        <smart-tree-item routerLink="/e-commerce-list"><a>List</a> <span
                                class="smart-badge smart-badge-danger">New</span></smart-tree-item>
                        <smart-tree-item routerLink="/e-commerce-checkout"><a>Checkout</a>
                            <span class="smart-badge smart-badge-danger">New</span></smart-tree-item>
                    </smart-tree-items-group>

                    <smart-tree-items-group>Analytics
                        <smart-tree-item routerLink="/analytics"><a>Dashboard</a></smart-tree-item>
                    </smart-tree-items-group>

                    <smart-tree-items-group>Projects
                        <smart-tree-item routerLink="/projects-list-1"><a>List 1</a>
                        </smart-tree-item>
                        <smart-tree-item routerLink="/projects-list-2"><a>List 2</a> <span
                                class="smart-badge smart-badge-danger">New</span></smart-tree-item>
                        <smart-tree-item routerLink="/detail"><a>Detail</a></smart-tree-item>
                    </smart-tree-items-group>

                    <smart-tree-items-group>Crypto
                        <smart-tree-item routerLink="/crypto"><a>Dashboard</a></smart-tree-item>
                    </smart-tree-items-group>

                    <smart-tree-items-group>Profile
                        <smart-tree-item routerLink="/profile-1"><a>Overview 1</a></smart-tree-item>
                        <smart-tree-item routerLink="/profile-2"><a>Overview 2</a> <span
                                class="smart-badge smart-badge-danger">New</span></smart-tree-item>
                        <smart-tree-item routerLink="/users-list"><a>Users</a> <span
                                class="smart-badge smart-badge-danger">New</span></smart-tree-item>
                        <smart-tree-item routerLink="/social"><a>Social Page</a></smart-tree-item>
                        <smart-tree-item routerLink="/settings"><a>Account Settings</a>
                        </smart-tree-item>
                    </smart-tree-items-group>

                    <smart-tree-items-group>Kanban
                        <smart-tree-item routerLink="/tasks"><a>Tasks 1</a></smart-tree-item>
                        <smart-tree-item routerLink="/tasks-2"><a>Tasks 2</a> <span
                                class="smart-badge smart-badge-danger">New</span></smart-tree-item>
                    </smart-tree-items-group>

                    <smart-tree-item routerLink="/chat"><a>Chat</a></smart-tree-item>
                    <smart-tree-item routerLink="/inbox"><a>Inbox</a> <span
                            class="smart-badge smart-badge-danger">New</span>
                    </smart-tree-item>
                </smart-tree-items-group>

                <smart-tree-items-group>
                    <span class="material-icons">contact_page</span> <span class="label-name">Pages</span>
                    <smart-tree-item routerLink="/sign-in"><a>Sign In</a></smart-tree-item>
                    <smart-tree-item routerLink="/sign-up"><a>Sign Up</a></smart-tree-item>
                    <smart-tree-item routerLink="/reset-password"><a>Reset Password</a></smart-tree-item>

                    <smart-tree-item routerLink="/invoice"><a>Invoice</a></smart-tree-item>
                    <smart-tree-item routerLink="/pricing"><a>Pricing</a></smart-tree-item>

                    <smart-tree-item routerLink="/404"><a>404 Page</a></smart-tree-item>
                    <smart-tree-item routerLink="/500"><a>500 Page</a></smart-tree-item>

                    <smart-tree-item routerLink="/knowledge-base"><a>Knowledge Base</a> <span
                            class="smart-badge smart-badge-danger">New</span></smart-tree-item>

                    <smart-tree-item routerLink="/blank"><a>Blank Page</a></smart-tree-item>
                </smart-tree-items-group>

                <smart-tree-items-group>
                    <span class="material-icons">library_books</span> <span class="label-name">Documentation</span>
                    <smart-tree-item routerLink="/introduction"><a>Introduction</a></smart-tree-item>
                    <smart-tree-item routerLink="/getting-started"><a>Getting Started</a></smart-tree-item>
                    <smart-tree-item routerLink="/plugins"><a>Plugins</a></smart-tree-item>
                    <smart-tree-item routerLink="/changelog"><a>Changelog</a></smart-tree-item>
                </smart-tree-items-group>

                <smart-tree-item id="toolsLabel" label="TOOLS & COMPONENTS" class="group-label"></smart-tree-item>

                <smart-tree-items-group>
                    <span class="material-icons">grid_on</span> <span class="label-name">UI Elements</span>
                    <smart-tree-item routerLink="/toasts"><a>Toasts</a></smart-tree-item>
                    <smart-tree-item routerLink="/buttons"><a>Buttons</a></smart-tree-item>
                    <smart-tree-item routerLink="/cards"><a>Cards</a></smart-tree-item>
                    <smart-tree-item routerLink="/carousel"><a>Carousel</a></smart-tree-item>
                    <smart-tree-item routerLink="/embed-video"><a>Embed Video</a></smart-tree-item>
                    <smart-tree-item routerLink="/general"><a>General</a></smart-tree-item>
                    <smart-tree-item routerLink="/grid-layout"><a>Grid Layout</a></smart-tree-item>
                    <smart-tree-item routerLink="/modals"><a>Modals</a></smart-tree-item>
                    <smart-tree-item routerLink="/tabs"><a>Tabs</a></smart-tree-item>
                    <smart-tree-item routerLink="/typography"><a>Typography</a></smart-tree-item>
                </smart-tree-items-group>

                <smart-tree-items-group>
                    <span class="material-icons">favorite</span> <span class="label-name">Icons</span>
                    <smart-tree-item routerLink="/feather"><a>Feather</a></smart-tree-item>
                    <smart-tree-item routerLink="/font-awesome"><a>Font Awesome</a></smart-tree-item>
                </smart-tree-items-group>

                <smart-tree-items-group>
                    <span class="material-icons">fact_check</span> <span class="label-name">Forms</span>
                    <smart-tree-item routerLink="/layouts"><a>Layouts</a></smart-tree-item>
                    <smart-tree-item routerLink="/basic-inputs"><a>Basic Inputs</a></smart-tree-item>
                    <smart-tree-item routerLink="/input-groups"><a>Input Groups</a></smart-tree-item>
                </smart-tree-items-group>

                <smart-tree-item routerLink="/tables">
                    <span class="material-icons">table_chart</span><a><span class="label-name">Tables</span></a>
                </smart-tree-item>

                <smart-tree-item id="pluginLabel" label="PLUGIN & ADDONS" class="group-label"></smart-tree-item>

                <smart-tree-items-group>
                    <span class="material-icons">fact_check</span> <span class="label-name">Form Plugins</span>
                    <smart-tree-item routerLink="/advanced-inputs"><a>Advanced Inputs</a></smart-tree-item>
                    <smart-tree-item routerLink="/editor"><a>Editor</a></smart-tree-item>
                    <smart-tree-item routerLink="/validation"><a>Validation</a></smart-tree-item>
                    <smart-tree-item routerLink="/wizard"><a>Wizard</a></smart-tree-item>
                </smart-tree-items-group>

                <smart-tree-items-group>
                    <span class="material-icons">table_chart</span> <span class="label-name">Data Tables</span>
                    <smart-tree-item routerLink="/responsive-table"><a>Responsive Table</a></smart-tree-item>
                    <smart-tree-item routerLink="/table-with-buttons"><a>Table with Buttons</a></smart-tree-item>
                    <smart-tree-item routerLink="/column-search"><a>Column Search</a></smart-tree-item>
                    <smart-tree-item routerLink="/multi-selection"><a>Multi Selection</a></smart-tree-item>
                    <smart-tree-item routerLink="/ajax-data"><a>Ajax Sourced Data</a></smart-tree-item>
                </smart-tree-items-group>

                <smart-tree-item routerLink="/charts">
                    <span class="material-icons">pie_chart</span><a><span class="label-name">Charts</span></a>
                </smart-tree-item>

                <smart-tree-item routerLink="/notifications">
                    <span class="material-icons">alarm</span><a><span class="label-name">Notifications</span></a>
                </smart-tree-item>

                <smart-tree-items-group>
                    <span class="material-icons">place</span> <span class="label-name">Maps</span>
                    <smart-tree-item routerLink="/google-maps"><a>Google Maps</a></smart-tree-item>
                </smart-tree-items-group>

                <smart-tree-item routerLink="/scheduler">
                    <span class="material-icons">calendar_today</span><a><span class="label-name">Scheduler</span></a>
                </smart-tree-item>

                <smart-tree-items-group>
                    <span class="material-icons">share</span> <span class="label-name">Multi Level</span>
                    <smart-tree-items-group>Two Levels
                        <smart-tree-item>Item 1</smart-tree-item>
                        <smart-tree-item>Item 2</smart-tree-item>
                    </smart-tree-items-group>
                    <smart-tree-items-group>Three Levels
                        <smart-tree-items-group>Item 1
                            <smart-tree-item>Item 1</smart-tree-item>
                            <smart-tree-item>Item 2</smart-tree-item>
                        </smart-tree-items-group>
                        <smart-tree-item>Item 2</smart-tree-item>
                    </smart-tree-items-group>
                </smart-tree-items-group>
            </smart-tree>
        </div>
        <smart-tooltip id="usageTooltipNormal" selector="toggleButton" position="right" class="animation">
            <span class="show">Open Sidebar</span>
            <span class="hide">Close Sidebar</span>
        </smart-tooltip>
    </aside>
</ng-container>
