// templates/admin-template-angular/src/app/core/footer/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'sm-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss']
})
export class FooterComponent {

  constructor() { }
}

<div class="footer">
    <div class="footer-nav">
        <a href="https://www.htmlelements.com/forums/" target="_blank">Support</a>
        <a href="https://www.htmlelements.com/faq/" target="_blank">Help Center</a>
        <a href="https://www.htmlelements.com/privacy-policy/" target="_blank">Privacy</a>
        <a href="https://www.htmlelements.com/terms-of-use/" target="_blank">Terms of Service</a>
    </div>
    <div>© 2021 - <a href="https://www.htmlelements.com/" target="_blank">jQWidgets LTD</a></div>
</div>

// templates/admin-template-react/src/Components/Core/Footer/Footer.js
function Footer() {
    return (
        <div className="footer">
            <div className="nav">
                <a href="https://www.htmlelements.com/forums/" target="_blank" rel="noreferrer">Support</a>
                <a href="https://www.htmlelements.com/faq/" target="_blank" rel="noreferrer">Help Center</a>
                <a href="https://www.htmlelements.com/privacy-policy/" target="_blank" rel="noreferrer">Privacy</a>
                <a href="https://www.htmlelements.com/terms-of-use/" target="_blank" rel="noreferrer">Terms of Service</a>
            </div>
            <div>© 2021 - <a href="https://www.htmlelements.com/" target="_blank" rel="noreferrer">jQWidgets LTD</a></div>
        </div>
    )
}

export default Footer
