// templates/admin-template-react/src/Pages/DataTables/ResponsiveTable/ResponsiveTable.js
import './ResponsiveTable.scss';
import { useEffect } from 'react';

import withAnimation from '../../../hoc/withAnimation';

import { Table } from '../../../smartImports';

import { defaultTitle } from '../../../contexts/themeContext';

import { generateData } from '../../../services/dataService';

function ResponsiveTable() {

    useEffect(() => { document.title = `Responsive Table - ${defaultTitle}` }, []);

    const tableData = {
        dataSource: new window.Smart.DataAdapter({
            dataSource: generateData(50),
            dataFields: [
                'id: number',
                'firstName: string',
                'lastName: string',
                'productName: string',
                'quantity: number',
                'price: number',
                'total: number'
            ]
        }),
        onLoad() {
            this.sortBy('lastName', 'asc');
        },
        paging: true,
        sortMode: 'one',
        tooltip: true,
        columns: [
            { label: 'id', dataField: 'id', dataType: 'number' },
            { label: 'First Name', dataField: 'firstName', dataType: 'string', responsivePriority: 4 },
            { label: 'Last Name', dataField: 'lastName', dataType: 'string' },
            { label: 'Product Name', dataField: 'productName', dataType: 'string' },
            { label: 'Quantity', dataField: 'quantity', dataType: 'number', responsivePriority: 3 },
            { label: 'Price', dataField: 'price', dataType: 'number', responsivePriority: 3 },
            { label: 'Total', dataField: 'total', dataType: 'number' }
        ]
    }

    return (
        <div className="container responsive-table-page">
            <div className="row">
                <div className="col-12 mb-3"><h4>Responsive Table</h4></div>
            </div>

            <div className="row">
                <div className="col">
                    <div className="card">
                        <div className="card-body">
                            <p>Smart.Table web component can be used to wrap or replace standard Tables.</p>
                            <Table
                                id="table"
                                {...tableData}
                            ></Table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default withAnimation(ResponsiveTable)

// templates/admin-template-angular/src/app/pages/data-tables/responsive-table/responsive-table.component.ts
import { Component, ViewChild } from '@angular/core';
import { TableComponent } from 'smart-webcomponents-angular/table';
import { DataService } from 'src/app/services/data.service';

@Component({
  selector: 'sm-responsive-table',
  templateUrl: './responsive-table.component.html',
  styleUrls: ['./responsive-table.component.scss']
})
export class ResponsiveTableComponent {

  @ViewChild('responsiveTable', { read: TableComponent, static: false }) responsiveTable!: TableComponent;

  tableSettings = {
    dataSource: new window.Smart.DataAdapter({
      dataSource: this.dataService.generateData(50),
      dataFields: [
        'id: number',
        'firstName: string',
        'lastName: string',
        'productName: string',
        'quantity: number',
        'price: number',
        'total: number'
      ]
    }),
    onInit: () => {

      this.responsiveTable.sortBy('lastName', 'asc');
      
    },
    paging: true,
    sortMode: 'one',
    tooltip: true,
    columns: [
      { label: 'id', dataField: 'id', dataType: 'number' },
      { label: 'First Name', dataField: 'firstName', dataType: 'string', responsivePriority: 4 },
      { label: 'Last Name', dataField: 'lastName', dataType: 'string' },
      { label: 'Product Name', dataField: 'productName', dataType: 'string' },
      { label: 'Quantity', dataField: 'quantity', dataType: 'number', responsivePriority: 3 },
      { label: 'Price', dataField: 'price', dataType: 'number', responsivePriority: 3 },
      { label: 'Total', dataField: 'total', dataType: 'number' }
    ]
  }
  constructor(private dataService: DataService) { }

}

<div class="container responsive-table">
    <div class="custom-row">
        <div class="responsive-table-header custom-col">
            <h4>Responsive Table</h4>
        </div>
    </div>

    <div class="custom-row">
        <div class="custom-col">
            <div class="custom-card">
                <div class="card-body">
                    <p>Smart.Table web component can be used to wrap or replace standard Tables.</p>
                    <smart-table #responsiveTable id="responsive-table-table"
                        [dataSource]="tableSettings.dataSource"
                        [paging]="tableSettings.paging"
                        [sortMode]="tableSettings.sortMode"
                        [tooltip]="tableSettings.tooltip"
                        [onInit]="tableSettings.onInit"
                        [columns]="tableSettings.columns">
                    </smart-table>
                </div>
            </div>
        </div>
    </div>
</div>
