// templates/admin-template-react/src/Pages/Pages/SignUp/SignUp.js
import { useEffect } from 'react';

import withAnimation from '../../../hoc/withAnimation';

import { Button, Input, PasswordTextBox } from '../../../smartImports';

import { defaultTitle } from '../../../contexts/themeContext';

function SignUp() {

    useEffect(() => { document.title = `Sign Up - ${defaultTitle}` }, []);

    return (
        <div className="container">
            <div className="text-center my-5">
                <h2>Welcome!</h2>
                <p>Sign up for the best user experience</p>
            </div>

            <div className="row">
                <div className="col-md-4 mx-auto">
                    <div className="card shadow-5">
                        <div className="card-body">
                            <div className="form-group">
                                <label className="d-block">Name</label>
                                <Input className="w-100" placeholder="Enter your name"></Input>
                            </div>

                            <div className="form-group">
                                <label className="d-block">Company</label>
                                <Input className="w-100" placeholder="Enter your company name"></Input>
                            </div>

                            <div className="form-group">
                                <label className="d-block">Email</label>
                                <Input className="w-100" placeholder="Enter your email"></Input>
                            </div>

                            <div className="form-group">
                                <label className="d-block">Password</label>
                                <PasswordTextBox className="w-100" placeholder="Enter a password"></PasswordTextBox>
                            </div>

                            <div className="text-center">
                                <Button className="primary">Sign up</Button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default withAnimation(SignUp)

// templates/admin-template-angular/src/app/pages/pages/sign-up/sign-up.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'sm-sign-up',
  templateUrl: './sign-up.component.html',
  styleUrls: ['./sign-up.component.scss']
})
export class SignUpComponent {

  constructor() { }

}

<div class="container sign-up">
    <div class="sign-up-header">
        <h2>Welcome!</h2>
        <p>Sign up for the best user experience</p>
    </div>

    <div class="sign-up-body custom-row">
        <div class="card-wrapper custom-col">
            <div class="card-shadow">
                <div class="card-body">
                    <div class="form-group">
                        <label>Name</label>
                        <smart-input placeholder="Enter your name"></smart-input>
                    </div>

                    <div class="form-group">
                        <label>Company</label>
                        <smart-input placeholder="Enter your company name"></smart-input>
                    </div>

                    <div class="form-group">
                        <label>Email</label>
                        <smart-input placeholder="Enter your email"></smart-input>
                    </div>

                    <div class="form-group">
                        <label>Password</label>
                        <smart-password-text-box placeholder="Enter a password"></smart-password-text-box>
                    </div>

                    <div class="text-center">
                        <smart-button class="primary">Sign up</smart-button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
