// templates/admin-template-angular/src/app/pages/pages/sign-in/sign-in.component.ts
import { Component, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'sm-sign-in',
  templateUrl: './sign-in.component.html',
  styleUrls: ['./sign-in.component.scss'],
  encapsulation: ViewEncapsulation.None
})
export class SignInComponent {

  constructor() { }
  
}

<div class="container sign-in">
    <div class="sign-in-header">
        <h2>Welcome back, John!</h2>
        <p>Please sign in to your account to continue</p>
    </div>

    <div class="sign-in-body custom-row">
        <div class="card-wrapper custom-col">
            <div class="card-shadow">
                <div class="card-body">
                    <div class="img-as-background">
                        <img src="../../../../assets/images/phonebook/mark.png">
                    </div>

                    <div class="form-group">
                        <label>Email</label>
                        <smart-input></smart-input>
                    </div>

                    <div class="form-group">
                        <label>Password</label>
                        <smart-password-text-box></smart-password-text-box>
                        <a href="#" class="small">Forgot your password?</a>
                    </div>

                    <div class="form-group">
                        <smart-check-box [checked]="true">Remember me</smart-check-box>
                    </div>

                    <div class="text-center">
                        <smart-button class="primary">Sign in</smart-button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

// templates/admin-template-react/src/Pages/Pages/SignIn/SignIn.js
import { useEffect } from 'react';

import withAnimation from '../../../hoc/withAnimation';

import { Button, Input, PasswordTextBox, CheckBox } from '../../../smartImports';

import { defaultTitle } from '../../../contexts/themeContext';

function SignIn() {

    useEffect(() => { document.title = `Sign In - ${defaultTitle}` }, []);

    return (
        <div className="container">
            <div className="text-center my-5">
                <h2>Welcome back, John!</h2>
                <p>Please sign in to your account to continue</p>
            </div>

            <div className="row">
                <div className="col-md-4 mx-auto">
                    <div className="card shadow-5">
                        <div className="card-body">
                            <div className="img-as-background square rounded-circle w-125 mx-auto mb-4">
                                <img src="assets/images/phonebook/mark.png" alt='avatar'/>
                            </div>

                            <div className="form-group">
                                <label className="d-block">Email</label>
                                <Input className="w-100"></Input>
                            </div>

                            <div className="form-group">
                                <label className="d-block">Password</label>
                                <PasswordTextBox className="w-100"></PasswordTextBox>
                                <a href="#" className="small">Forgot your password?</a>
                            </div>

                            <div className="form-group">
                                <CheckBox checked>Remember me</CheckBox>
                            </div>

                            <div className="text-center">
                                <Button className="primary">Sign in</Button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default withAnimation(SignIn)
