// templates/admin-template-angular/src/app/core/header/header.component.ts
import { AfterViewInit, Component, EventEmitter, Input, Output, ViewEncapsulation } from '@angular/core';
import { Menu } from 'smart-webcomponents-angular/menu';
import { SidebarToggleOptions } from 'src/app/services/sidebar.service';

@Component({
  selector: 'sm-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'],
  encapsulation: ViewEncapsulation.None
})
export class HeaderComponent implements AfterViewInit {

  @Input('isSidebarExpanded') isSidebarExpanded!: boolean;
  @Output() onToggle = new EventEmitter<SidebarToggleOptions>();

  isLeftNavigationOpenedOnMobile: boolean = false;
  isRightNavigationOpenedOnMobile: boolean = false;

  toggleSidebar(): void {
    this.onToggle.emit({
      expansionPreference: !this.isSidebarExpanded,
      forMobile: window.innerWidth < 767 ? true : false
    });
  }

  stopPropagation($event: Event) {

    $event.stopPropagation();

  }

  closeMenu($event: any, menu: Menu) {

    if ($event!.target!.closest('[template-applied]')) {

      menu.close();

    }

  }

  ngAfterViewInit(): void {
      
  }

  toggleMenu(button: HTMLElement, menu: Menu) {

    const rect = button.getBoundingClientRect();

    Array.from(document.getElementsByTagName('smart-menu'))
      .filter(currentMenu => currentMenu !== menu)
      .forEach(menu => menu.close());

    document.querySelectorAll('.dropdown-menu-show').forEach(e => {
      e.classList.remove('dropdown-menu-show');
    });

    document.querySelectorAll('.dropdown-button')
      .forEach(menu => menu.classList.remove('dropdown-button-active'));

    if (!menu.opened) {

      menu.open(rect.right - menu.offsetWidth, rect.bottom + window.scrollY + 0.5);

    } else {

      menu.close();

    }
  }

  toggleNavigationOnMobile(navigation: string, navigationElement: HTMLElement) {

    if (navigation == 'left') {

      navigationElement.classList.toggle('navigation-left-visible')

    } else if (navigation == 'right') {

      navigationElement.classList.toggle('navigation-right-visible')

    }

  }

  animate() {
    
  }
}

<ng-container>
    <div class="header-header" [class.header-sidebar-not-expanded]="!isSidebarExpanded">
        <div class="navigation-mobile js-mobile-menu">
            <div class="logo">
                <a href="./"><img src="../../../assets/images/logo-htmlelements.svg" /></a>
            </div>

            <ul class="nav">
                <li class="nav-item menu-account" (click)="toggleNavigationOnMobile('right', navigationRight)">
                    <span class="material-icons">person</span>
                </li>

                <li class="nav-item menu-additional" (click)="toggleNavigationOnMobile('left', navigationLeft)">
                    <span class="material-icons">more_horiz</span>
                </li>

                <li class="nav-item main-menu" (click)="toggleSidebar()">
                    <span class="material-icons">menu</span>
                </li>
            </ul>
        </div>

        <ul #navigationLeft class="nav navigation-left">
            <li>
                <a routerLink="/" (click)="animate()">Dashboard</a>
            </li>
            <li class="nav-item active">
                <a>Pages</a>
            </li>
            <li>
                <a>Features</a>
            </li>
            <li>
                <a>App</a>
            </li>
        </ul>

        <ul #navigationRight class="nav navigation-right">
            <li #messagesButton id="messages" (pointerup)="stopPropagation($event)"
                (click)="toggleMenu(messagesButton, messagesMenu)">
                <span class="position-relative">
                    <span class="material-icons">message</span>
                    <span class="cnt">3</span>
                </span>
            </li>
            <li #notificationsButton (pointerup)="stopPropagation($event)"
                (click)="toggleMenu(notificationsButton, notificationsMenu)">
                <span class="material-icons">notifications_off</span>
            </li>
            <li #languagesButton (pointerup)="stopPropagation($event)"
                (click)="toggleMenu(languagesButton, languagesMenu)">
                <img src="https://img.icons8.com/office/30/000000/usa.png" />
            </li>
            <li #searchButton (pointerup)="stopPropagation($event)" (click)="toggleMenu(searchButton, searchMenu)">
                <span class="material-icons">search</span>
            </li>

            <li #profileButton (pointerup)="stopPropagation($event)" (click)="toggleMenu(profileButton, profileMenu)">
                <div class="holder">
                    <div class="avatar" style="background-image: url('../../../assets/images/phonebook/mark.png');">
                    </div>
                </div>
            </li>
        </ul>
    </div>

    <smart-menu #messagesMenu id="messagesMenu" class="dashboard1-menu smart-custom-dropdown-menu" mode="dropDown"
        (pointerUp)="closeMenu($event, messagesMenu)">
        <smart-menu-item label="newMessages" class="menu-header">
            <strong>3 New Messages</strong>
        </smart-menu-item>

        <smart-menu-item>
            <div class="message-wrapper">
                <div class="message-logo-wrapper">
                    <div class="img-as-background">
                        <img src="../../../assets/images/phonebook/michael.png" />
                    </div>
                </div>
                <div class="message-info-wrapper">
                    <div class="name font-weight-bold">Frederick Murphy</div>
                    <div class="content text-break-line-2">Lorem ipsum dolor sit amet.</div>
                    <small class="time text-muted">7 min ago</small>
                </div>
            </div>
        </smart-menu-item>

        <smart-menu-item>
            <div class="message-wrapper">
                <div class="message-logo-wrapper">
                    <div class="img-as-background">
                        <img src="../../../assets/images/phonebook/maya.png" />
                    </div>
                </div>
                <div class="message-info-wrapper">
                    <div class="name font-weight-bold">Eva Hayes</div>
                    <div class="content text-break-line-2">Nulla porta, risus in suscipit tincidunt.</div>
                    <small class="time text-muted">15 min ago</small>
                </div>
            </div>
        </smart-menu-item>

        <smart-menu-item>
            <div class="message-wrapper">
                <div class="message-logo-wrapper">
                    <div class="img-as-background">
                        <img src="../../../assets/images/phonebook/maria.png" />
                    </div>
                </div>
                <div class="message-info-wrapper">
                    <div class="name font-weight-bold">Joyce Scott</div>
                    <div class="content text-break-line-2">Maecenas eleifend, nunc eu convallis mollis, ante lacus
                        euismod elit, iaculis tempor ex
                        sapien quis est.
                    </div>
                    <small class="time text-muted">Yesterday</small>
                </div>
            </div>
        </smart-menu-item>

        <smart-menu-item label="Show all messages" class="menu-footer"></smart-menu-item>
    </smart-menu>

    <smart-menu #notificationsMenu class="dashboard1-menu smart-custom-dropdown-menu" mode="dropDown"
        (pointerUp)="closeMenu($event, notificationsMenu)">
        <smart-menu-item label="newNotifications" class="menu-header">
            <strong>4 New Notifications</strong>
        </smart-menu-item>
        <smart-menu-item>
            <div class="notification-wrapper">
                <div class="notification-logo-wrapper">
                    <span class="material-icons text-warning notification-logo">stay_current_portrait</span>
                </div>

                <div class="notification-info-wrapper">
                    <div class="name font-weight-bold">New device detected</div>
                    <div class="content text-break-line-2">Login from a new device has been detected.</div>
                    <small class="time text-muted">2 hours ago</small>
                </div>
            </div>
        </smart-menu-item>

        <smart-menu-item>
            <div class="notification-wrapper">
                <div class="notification-logo-wrapper">
                    <span class="material-icons text-primary notification-logo">person_add</span>
                </div>

                <div class="notification-info-wrapper">
                    <div class="name font-weight-bold">Friend request</div>
                    <div class="content text-break-line-2">Joyce Scott has been added as a friend.</div>
                    <small class="time text-muted">3 hours ago</small>
                </div>
            </div>
        </smart-menu-item>
        <smart-menu-item>
            <div class="notification-wrapper">
                <div class="notification-logo-wrapper">
                    <span class="material-icons text-danger notification-logo">healing</span>
                </div>

                <div class="notification-info-wrapper">
                    <div class="name font-weight-bold">Downtime</div>
                    <div class="content text-break-line-2">Our servers will undertake maintenance tomorrow.</div>
                    <small class="time text-muted">Yesterday</small>
                </div>
            </div>
        </smart-menu-item>
        <smart-menu-item>
            <div class="notification-wrapper">
                <div class="notification-logo-wrapper">
                    <span class="material-icons text-primary notification-logo">person_add</span>
                </div>

                <div class="notification-info-wrapper">
                    <div class="name font-weight-bold">Friend request</div>
                    <div class="content text-break-line-2">Nathan Hoffman has been added as a friend.</div>
                    <small class="time text-muted">3 days ago</small>
                </div>
            </div>
        </smart-menu-item>
        <smart-menu-item label="Show all notifications" class="menu-footer"></smart-menu-item>
    </smart-menu>

    <smart-menu #languagesMenu class="dashboard1-menu smart-custom-dropdown-menu" mode="dropDown"
        (pointerUp)="closeMenu($event, languagesMenu)">
        <smart-menu-item>
            <div class="language-text"><img src="https://img.icons8.com/office/30/000000/usa.png" class="mr-3" />
                English
            </div>
        </smart-menu-item>
        <smart-menu-item>
            <div class="language-text"><img src="https://img.icons8.com/office/30/000000/china.png" class="mr-3" />
                Chinese
            </div>
        </smart-menu-item>
        <smart-menu-item>
            <div class="language-text"><img src="https://img.icons8.com/office/30/000000/spain.png" class="mr-3" />
                Spanish
            </div>
        </smart-menu-item>
        <smart-menu-item>
            <div class="language-text"><img src="https://img.icons8.com/office/30/000000/india.png" class="mr-3" />
                Hindi
            </div>
        </smart-menu-item>
        <smart-menu-item>
            <div class="language-text"><img src="https://img.icons8.com/office/30/000000/russian-federation.png"
                    class="mr-3" /> Russian</div>
        </smart-menu-item>
    </smart-menu>

    <smart-menu #searchMenu class="dashboard1-menu smart-custom-dropdown-menu" mode="dropDown"
        (pointerUp)="closeMenu($event, searchMenu)">
        <smart-menu-item>
            <span class="material-icons">search</span>
            <smart-input class="search-input" placeholder="Search something..." autofocus="true"></smart-input>
        </smart-menu-item>
    </smart-menu>

    <smart-menu #profileMenu class="dashboard1-menu smart-custom-dropdown-menu" mode="dropDown"
        (pointerUp)="closeMenu($event, profileMenu)">
        <smart-menu-item>
            <span class="material-icons profile-icon">supervised_user_circle</span> Profile
        </smart-menu-item>
        <smart-menu-item [separator]="true">
            <span class="material-icons profile-icon">pie_chart</span>Analytics
        </smart-menu-item>
        <smart-menu-item>Settings & Privacy</smart-menu-item>
        <smart-menu-item>Help</smart-menu-item>
        <smart-menu-item>Sign out</smart-menu-item>
    </smart-menu>

</ng-container>

// templates/admin-template-react/src/Components/Core/Header/Header.js
import { useRef } from 'react'
import './Header.scss'
import { Menu, MenuItem, Input } from '../../../smartImports';
import { Link } from 'react-router-dom';

function Header() {

    const messagesMenuRef = useRef();
    const notificationsMenuRef = useRef();
    const languageMenuRef = useRef();
    const searchMenuRef = useRef();
    const profileMenuRef = useRef();
    
    const toggleMenu = (menu, e) => {

        menu = menu.current;

        const rect = e.currentTarget.getBoundingClientRect();

        Array.from(document.getElementsByTagName('smart-menu'))
            .filter(smartMenu => smartMenu !== menu.nativeElement)
            .forEach(menu => menu.close());

        if (!menu.opened) {

            menu.open(rect.right - menu.nativeElement.offsetWidth, rect.bottom + window.scrollY);

        } else {

            menu.close();

        }

    }

    return (
        <>
            <div className="header">
                <div className="navigation-mobile js-mobile-menu">
                    <div className="logo">
                        <a href="./"><img alt="" src="assets/images/logo-htmlelements.svg" /></a>
                    </div>

                    <ul className="nav">
                        <li
                            className="nav-item px-1 px-sm-3 js-menu-account"
                            onClick={() => document.body.classList.toggle('mobile-menu-account-activated')}
                        >
                            <span className="material-icons">person</span>
                        </li>

                        <li
                            className="nav-item px-1 px-sm-3 js-menu-additional"
                            onClick={() => document.body.classList.toggle('mobile-menu-additional-activated')}
                        >
                            <span className="material-icons">more_horiz</span>
                        </li>

                        <li
                            className="nav-item px-1 px-sm-3 js-main-menu"
                            onClick={() => document.body.classList.toggle('mobile-menu-activated')}
                        >
                            <span className="material-icons">menu</span>
                        </li>
                    </ul>
                </div >

                <ul className="nav navigation-left">
                    <li className="nav-item">
                        <Link to='/' className="nav-link">Dashboard</Link>
                    </li>
                    <li className="nav-item active">
                        <a href="#" onClick={(e) => e.preventDefault()} className="nav-link">Pages</a>
                    </li>
                    <li className="nav-item">
                        <a href="#" onClick={(e) => e.preventDefault()} className="nav-link">Features</a>
                    </li>
                    <li className="nav-item">
                        <a href="#" onClick={(e) => e.preventDefault()} className="nav-link">App</a>
                    </li>
                </ul>

                <ul className="nav navigation-right">
                    <li
                        onClick={toggleMenu.bind(null, messagesMenuRef)}
                        onPointerUp={(e) => e.stopPropagation()}
                        className="nav-item px-3 messages"
                        id="messages"
                    >
                        <span className="position-relative">
                            <span className="material-icons">message</span>
                            <span className="cnt">3</span>
                        </span>
                    </li>
                    <li
                        onClick={toggleMenu.bind(null, notificationsMenuRef)}
                        onPointerUp={(e) => e.stopPropagation()}
                        className="nav-item px-3 notifications"
                        id="notifications"
                    >
                        <span className="material-icons">notifications_off</span>
                    </li>
                    <li
                        onClick={toggleMenu.bind(null, languageMenuRef)}
                        onPointerUp={(e) => e.stopPropagation()}
                        className="nav-item px-3"
                        id="language"
                    >
                        <img alt="" src="https://img.icons8.com/office/30/000000/usa.png" />
                    </li>
                    <li
                        onClick={toggleMenu.bind(null, searchMenuRef)}
                        onPointerUp={(e) => e.stopPropagation()}
                        className="nav-item px-3 search"
                        id="search"
                    >
                        <span className="material-icons">search</span>
                    </li>

                    <li
                        onClick={toggleMenu.bind(null, profileMenuRef)}
                        onPointerUp={(e) => e.stopPropagation()}
                        className="nav-item px-3 profile"
                        id="profile"
                    >
                        <div className="holder">
                            <div
                                className="avatar rounded-circle profile-image"
                            ></div>
                        </div>
                    </li>
                </ul>
            </div>

            <Menu
                ref={messagesMenuRef}
                id="messagesMenu"
                className="smart-custom-dropdown-menu"
                mode="dropDown"
                onPointerUp={(e) =>
                    e.target.closest('[template-applied]') ?
                        e.currentTarget.close()
                        : {}
                }
            >
                <MenuItem label="newMessages" className="menu-header"></MenuItem>

                <MenuItem>
                    <div className="row row-mx-10 align-items-center">
                        <div className="col-auto col-px-10">
                            <div className="square img-as-background w-25px d-inline-block mr-2 rounded-circle">
                                <img alt="" src="assets/images/phonebook/michael.png" />
                            </div>
                        </div>
                        <div className="col col-px-10">
                            <div className="name font-weight-bold">Frederick Murphy</div>
                            <div className="content text-break-line-2">Lorem ipsum dolor sit amet.</div>
                            <small className="time text-muted">7 min ago</small>
                        </div>
                    </div>
                </MenuItem>

                <MenuItem>
                    <div className="row row-mx-10 align-items-center">
                        <div className="col-auto col-px-10">
                            <div className="square img-as-background w-25px d-inline-block mr-2 rounded-circle">
                                <img alt="" src="assets/images/phonebook/maya.png" />
                            </div>
                        </div>
                        <div className="col col-px-10">
                            <div className="name font-weight-bold">Eva Hayes</div>
                            <div className="content text-break-line-2">Nulla porta, risus in suscipit tincidunt.</div>
                            <small className="time text-muted">15 min ago</small>
                        </div>
                    </div>
                </MenuItem>

                <MenuItem>
                    <div className="row row-mx-10 align-items-center">
                        <div className="col-auto col-px-10">
                            <div className="square img-as-background w-25px d-inline-block mr-2 rounded-circle">
                                <img alt="" src="assets/images/phonebook/maria.png" />
                            </div>
                        </div>
                        <div className="col col-px-10">
                            <div className="name font-weight-bold">Joyce Scott</div>
                            <div className="content text-break-line-2">Maecenas eleifend, nunc eu convallis mollis, ante lacus
                                euismod elit, iaculis tempor ex
                                sapien quis est.
                            </div>
                            <small className="time text-muted">Yesterday</small>
                        </div>
                    </div>
                </MenuItem>

                <MenuItem label="showAllMessages" className="menu-footer"></MenuItem>
            </Menu>

            <Menu
                ref={notificationsMenuRef}
                id="notificationsMenu"
                className="smart-custom-dropdown-menu"
                mode="dropDown"
                onPointerUp={(e) =>
                    e.target.closest('[template-applied]') ?
                        e.currentTarget.close()
                        : {}
                }
            >
                <MenuItem label="newNotifications" className="menu-header"></MenuItem>
                <MenuItem>
                    <div className="row row-mx-10 align-items-center">
                        <div className="col-auto col-px-10">
                            <span className="material-icons text-warning ml-3">stay_current_portrait</span>
                        </div>

                        <div className="col col-px-10">
                            <div className="name font-weight-bold">New device detected</div>
                            <div className="content text-break-line-2">Login from a new device has been detected.</div>
                            <small className="time text-muted">2 hours ago</small>
                        </div>
                    </div>
                </MenuItem>

                <MenuItem>
                    <div className="row row-mx-10 align-items-center">
                        <div className="col-auto col-px-10">
                            <span className="material-icons text-primary ml-3">person_add</span>
                        </div>

                        <div className="col col-px-10">
                            <div className="name font-weight-bold">Friend request</div>
                            <div className="content text-break-line-2">Joyce Scott has been added as a friend.</div>
                            <small className="time text-muted">3 hours ago</small>
                        </div>
                    </div>
                </MenuItem>
                <MenuItem>
                    <div className="row row-mx-10 align-items-center">
                        <div className="col-auto col-px-10">
                            <span className="material-icons text-danger ml-3">healing</span>
                        </div>

                        <div className="col col-px-10">
                            <div className="name font-weight-bold">Downtime</div>
                            <div className="content text-break-line-2">Our servers will undertake maintenance tomorrow.</div>
                            <small className="time text-muted">Yesterday</small>
                        </div>
                    </div>
                </MenuItem>
                <MenuItem>
                    <div className="row row-mx-10 align-items-center">
                        <div className="col-auto col-px-10">
                            <span className="material-icons text-primary ml-3">person_add</span>
                        </div>

                        <div className="col col-px-10">
                            <div className="name font-weight-bold">Friend request</div>
                            <div className="content text-break-line-2">Nathan Hoffman has been added as a friend.</div>
                            <small className="time text-muted">3 days ago</small>
                        </div>
                    </div>
                </MenuItem>
                <MenuItem label="showAllNotifications" className="menu-footer"></MenuItem>
            </Menu>

            <Menu
                ref={languageMenuRef}
                id="languageMenu"
                className="smart-custom-dropdown-menu"
                mode="dropDown"
                onPointerUp={(e) =>
                    e.target.closest('[template-applied]') ?
                        e.currentTarget.close()
                        : {}
                }
            >
                <MenuItem>
                    <div className="pl-2 pr-3"><img alt="" src="https://img.icons8.com/office/30/000000/usa.png" className="mr-3" />
                        English</div>
                </MenuItem>
                <MenuItem>
                    <div className="pl-2 pr-3"><img alt="" src="https://img.icons8.com/office/30/000000/china.png" className="mr-3" />
                        Chinese</div>
                </MenuItem>
                <MenuItem>
                    <div className="pl-2 pr-3"><img alt="" src="https://img.icons8.com/office/30/000000/spain.png" className="mr-3" />
                        Spanish</div>
                </MenuItem>
                <MenuItem>
                    <div className="pl-2 pr-3"><img alt="" src="https://img.icons8.com/office/30/000000/india.png" className="mr-3" />
                        Hindi</div>
                </MenuItem>
                <MenuItem>
                    <div className="pl-2 pr-3"><img alt="" src="https://img.icons8.com/office/30/000000/russian-federation.png"
                        className="mr-3" /> Russian</div>
                </MenuItem>
            </Menu>

            <Menu
                ref={searchMenuRef}
                id="searchMenu"
                className="smart-custom-dropdown-menu"
                mode="dropDown"
                // onClosing={(e) =>
                //     e.detail.target.tagName === 'SMART-MENU-ITEM'
                //         ? e.preventDefault()
                //         : {}
                // }
                onPointerUp={(e) =>
                    e.target.closest('[template-applied]') ?
                        e.currentTarget.close()
                        : {}
                }
            >
                <MenuItem>
                    <span className="material-icons">search</span>
                    <Input placeholder="Search something..." autofocus="true"></Input>
                </MenuItem>
            </Menu>

            <Menu
                ref={profileMenuRef}
                id="profileMenu"
                className="smart-custom-dropdown-menu"
                mode="dropDown"
                onPointerUp={(e) =>
                    e.target.closest('[template-applied]') ?
                        e.currentTarget.close()
                        : {}
                }
            >
                <MenuItem><span className="material-icons mr-3">supervised_user_circle</span> Profile</MenuItem>
                <MenuItem separator><span className="material-icons mr-3">pie_chart</span>Analytics</MenuItem>
                <MenuItem>Settings & Privacy</MenuItem>
                <MenuItem>Help</MenuItem>
                <MenuItem>Sign out</MenuItem>
            </Menu>
        </>

    )
}

export default Header
