// templates/admin-template-angular/src/app/pages/ui-elements/carousel/carousel.component.ts
import { Component, OnInit, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'sm-carousel',
  templateUrl: './carousel.component.html',
  styleUrls: ['./carousel.component.scss'],
  encapsulation: ViewEncapsulation.None
})
export class CarouselComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="container carousel">
    <div class="custom-row">
        <div class="carousel-header custom-col">
            <h4>Carousel</h4>
        </div>
    </div>

    <div class="custom-row">
        <div class="carousel-entity custom-col">
            <div class="custom-card h-100">
                <div class="card-header">
                    <h4 class="label">Slides only</h4>
                </div>
                <div class="card-body">
                    <smart-carousel [autoPlay]="true" [dataSource]="[
                    { 'image': '../../../../assets/images/travel/4.jpg' }, { 'image'
                        : '../../../../assets/images/travel/5.jpg' }, { 'image'
                        : '../../../../assets/images/travel/6.jpg' }]" [hideArrows]="true" [hideIndicators]="true"
                        [interval]="2000" [loop]="true" [slideShow]="true"></smart-carousel>
                </div>
            </div>
        </div>
        <div class="carousel-entity custom-col">
            <div class="custom-card h-100">
                <div class="card-header">
                    <h4 class="label">With controls</h4>
                </div>
                <div class="card-body">
                    <smart-carousel [autoPlay]="true" [dataSource]="[{ '
                        image': '../../../../assets/images/travel/4.jpg' }, { 'image'
                        : '../../../../assets/images/travel/5.jpg' }, { 'image'
                        : '../../../../assets/images/travel/6.jpg' }]" [hideIndicators]="true" [interval]="5000"
                        [loop]="true" [slideShow]="true">
                    </smart-carousel>
                </div>
            </div>
        </div>
    </div>
    <div class="custom-row">
        <div class="carousel-entity custom-col">
            <div class="custom-card h-100">
                <div class="card-header">
                    <h4 class="label">With indicators</h4>
                </div>
                <div class="card-body">
                    <smart-carousel [autoPlay]="true" [dataSource]="[{ '
                        image': '../../../../assets/images/travel/4.jpg' }, { 'image'
                        : '../../../../assets/images/travel/5.jpg' }, { 'image'
                        : '../../../../assets/images/travel/6.jpg' }]" [interval]="5000" [loop]="true"
                        [slideShow]="true"></smart-carousel>
                </div>
            </div>
        </div>
        <div class="carousel-entity custom-col">
            <div class="custom-card h-100">
                <div class="card-header">
                    <h4 class="label">With captions</h4>
                </div>
                <div class="card-body">
                    <smart-carousel id="carouselWithCaptions" [autoPlay]="true" [dataSource]="[{ '
                        image': '../../../../assets/images/travel/4.jpg' , 'label' : 'Photo 1' }, { 'image'
                        : '../../../../assets/images/travel/5.jpg' , 'label' : 'Photo 2' }, { 'image'
                        : '../../../../assets/images/travel/6.jpg' , 'label' : 'Photo 3' }]" [interval]="5000"
                        [loop]="true" [slideShow]="true"></smart-carousel>
                </div>
            </div>
        </div>
    </div>
    <div class="custom-row">
        <div class="carousel-entity custom-col">
            <div class="custom-card h-100">
                <div class="card-header">
                    <h4 class="label">Slide animation</h4>
                </div>
                <div class="card-body">
                    <smart-carousel class="slide" [autoPlay]="true" [dataSource]="[{ '
                        image': '../../../../assets/images/travel/4.jpg' }, { 'image'
                        : '../../../../assets/images/travel/5.jpg' }, { 'image'
                        : '../../../../assets/images/travel/6.jpg' }]" [hideIndicators]="true" [interval]="5000"
                        [loop]="true" [slideShow]="true">
                    </smart-carousel>
                </div>
            </div>
        </div>
    </div>
</div>

// templates/admin-template-react/src/Pages/UIElements/Carousel/Carousel.js
import './Carousel.scss';
import { useEffect } from 'react';

import withAnimation from '../../../hoc/withAnimation';
import { Carousel } from '../../../smartImports';

import { defaultTitle } from '../../../contexts/themeContext';

function CarouselPage() {

    useEffect(() => { document.title = `Carousel - ${defaultTitle}` }, []);

    return (
        <div className="container carousel-page">
            <div className="row">
                <div className="col-12 mb-3"><h4>Carousel</h4></div>
            </div>

            <div className="row">
                <div className="col-lg-6 mb-5">
                    <div className="card h-100">
                        <div className="card-header">
                            <h4 className="label">Slides only</h4>
                        </div>
                        <div className="card-body">
                            <Carousel autoPlay dataSource={[{ "image": "assets/images/travel/4.jpg" }, { "image": "assets/images/travel/5.jpg" }, { "image": "assets/images/travel/6.jpg" }]}
                                hideArrows
                                hideIndicators
                                interval={2000}
                                loop
                                slideShow
                            ></Carousel>
                        </div>
                    </div>
                </div>
                <div className="col-lg-6 mb-5">
                    <div className="card h-100">
                        <div className="card-header">
                            <h4 className="label">With controls</h4>
                        </div>
                        <div className="card-body">
                            <Carousel
                                autoPlay
                                dataSource={[{ "image": "assets/images/travel/4.jpg" }, { "image": "assets/images/travel/5.jpg" }, { "image": "assets/images/travel/6.jpg" }]}
                                hideIndicators
                                interval={5000}
                                loop
                                slideShow></Carousel>
                        </div>
                    </div>
                </div>
            </div >
            <div className="row">
                <div className="col-lg-6 mb-5">
                    <div className="card h-100">
                        <div className="card-header">
                            <h4 className="label">With indicators</h4>
                        </div>
                        <div className="card-body">
                            <Carousel
                                autoPlay
                                dataSource={[{ "image": "assets/images/travel/4.jpg" }, { "image": "assets/images/travel/5.jpg" }, { "image": "assets/images/travel/6.jpg" }]}
                                interval={5000}
                                loop slideShow
                            ></Carousel>
                        </div>
                    </div>
                </div>
                <div className="col-lg-6 mb-5">
                    <div className="card h-100">
                        <div className="card-header">
                            <h4 className="label">With captions</h4>
                        </div>
                        <div className="card-body">
                            <Carousel
                                id="carouselWithCaptions"
                                autoPlay
                                dataSource={[{ "image": "assets/images/travel/4.jpg", "label": "Photo 1" }, { "image": "assets/images/travel/5.jpg", "label": "Photo 2" }, { "image": "assets/images/travel/6.jpg", "label": "Photo 3" }]}
                                interval={5000}
                                loop
                                slideShow
                            ></Carousel>
                        </div>
                    </div>
                </div >
            </div >
            <div className="row">
                <div className="col-lg-6 mb-5">
                    <div className="card h-100">
                        <div className="card-header">
                            <h4 className="label">Slide animation</h4>
                        </div>
                        <div className="card-body">
                            <Carousel
                                className="slide"
                                autoPlay
                                dataSource={[{ "image": "assets/images/travel/4.jpg" }, { "image": "assets/images/travel/5.jpg" }, { "image": "assets/images/travel/6.jpg" }]}
                                hideIndicators
                                interval={5000}
                                loop
                                slideShow
                            ></Carousel>
                        </div>
                    </div>
                </div>
            </div >
        </div >
    )
}

export default withAnimation(CarouselPage)
