// templates/admin-template-react/src/Pages/DataTables/TableWithButtons/TableWithButtons.js
import './TableWithButtons.scss';
import { useEffect } from 'react';

import withAnimation from '../../../hoc/withAnimation';

import { Table } from '../../../smartImports';

import { defaultTitle } from '../../../contexts/themeContext';

import { generateData } from '../../../services/dataService';

function TableWithButtons() {

    useEffect(() => { document.title = `Table With Buttons - ${defaultTitle}` }, []);

    const tableData = {
        dataSource: new window.Smart.DataAdapter({
            dataSource: generateData(50),
            dataFields: [
                'id: number',
                'firstName: string',
                'lastName: string',
                'productName: string',
                'quantity: number',
                'price: number'
            ]
        }),
        onLoad() {
            this.sortBy('lastName', 'asc');
        },
        filtering: true,
        paging: true,
        sortMode: 'one',
        tooltip: true,
        columns: [
            { label: 'id', dataField: 'id', dataType: 'number', responsivePriority: 3 },
            { label: 'First Name', dataField: 'firstName', dataType: 'string', responsivePriority: 4 },
            { label: 'Last Name', dataField: 'lastName', dataType: 'string' },
            { label: 'Product Name', dataField: 'productName', dataType: 'string' },
            { label: 'Quantity', dataField: 'quantity', dataType: 'number', responsivePriority: 3 },
            { label: 'Price', dataField: 'price', dataType: 'number', responsivePriority: 3 },
            {
                label: '', dataField: '', width: 155, formatFunction: function (settings) {
                    settings.template = '<div class="actions-container"><smart-button class="small-button outlined primary">Copy</smart-button><smart-button class="small-button outlined error">Remove</smart-button></div>';
                }
            }
        ]
    }

    return (
        <div className="container table-with-buttons-page">
            <div className="row">
                <div className="col-12 mb-3"><h4>Table With Buttons</h4></div>
            </div>

            <div className="card">
                <div className="card-body">
                    <Table
                        id="table"
                        {...tableData}
                    ></Table>
                </div>
            </div>
        </div>
    )
}

export default withAnimation(TableWithButtons)

// templates/admin-template-angular/src/app/pages/data-tables/table-with-buttons/table-with-buttons.component.ts
import { Component, OnInit, ViewChild, ViewEncapsulation } from '@angular/core';
import { TableComponent } from 'smart-webcomponents-angular/table';
import { DataService } from 'src/app/services/data.service';

@Component({
  selector: 'sm-table-with-buttons',
  templateUrl: './table-with-buttons.component.html',
  styleUrls: ['./table-with-buttons.component.scss'],
  encapsulation: ViewEncapsulation.None
})
export class TableWithButtonsComponent {

  @ViewChild('tableWithButtons', { read: TableComponent, static: false }) tableWithButtons!: TableComponent;

  tableWithButtonsSettings = {
    dataSource: new window.Smart.DataAdapter({
      dataSource: this.dataService.generateData(50),
      dataFields: [
        'id: number',
        'firstName: string',
        'lastName: string',
        'productName: string',
        'quantity: number',
        'price: number'
      ]
    }),
    onInit: () => {

      this.tableWithButtons.sortBy('lastName', 'asc');

    },
    filtering: true,
    paging: true,
    sortMode: 'one',
    tooltip: true,
    columns: [
      { label: 'id', dataField: 'id', dataType: 'number', responsivePriority: 3 },
      { label: 'First Name', dataField: 'firstName', dataType: 'string', responsivePriority: 4 },
      { label: 'Last Name', dataField: 'lastName', dataType: 'string' },
      { label: 'Product Name', dataField: 'productName', dataType: 'string' },
      { label: 'Quantity', dataField: 'quantity', dataType: 'number', responsivePriority: 3 },
      { label: 'Price', dataField: 'price', dataType: 'number', responsivePriority: 3 },
      {
        label: '', dataField: '', width: 155, formatFunction: function (settings: any) {
          settings.template = '<div class="actions-container"><smart-button class="small-button outlined primary">Copy</smart-button><smart-button class="small-button outlined error">Remove</smart-button></div>';
        }
      }
    ]
  }

  constructor(private dataService: DataService) { }

}

<div class="container table-with-buttons">
    <div class="custom-row">
        <div class="table-with-buttons-header custom-col">
            <h4>Table With Buttons</h4>
        </div>
    </div>

    <div class="custom-card">
        <div class="card-body">
            <smart-table #tableWithButtons id="table-with-buttons" [dataSource]="tableWithButtonsSettings.dataSource"
                [paging]="tableWithButtonsSettings.paging" [sortMode]="tableWithButtonsSettings.sortMode"
                [tooltip]="tableWithButtonsSettings.tooltip" [onInit]="tableWithButtonsSettings.onInit"
                [columns]="tableWithButtonsSettings.columns" [filtering]="tableWithButtonsSettings.filtering">
            </smart-table>
        </div>
    </div>
</div>
