// templates/admin-template-angular/src/app/pages/data-tables/multi-selection/multi-selection.component.ts
import { Component, ViewChild } from '@angular/core';
import { TableComponent } from 'smart-webcomponents-angular/table';
import { DataService } from 'src/app/services/data.service';

@Component({
  selector: 'sm-multi-selection',
  templateUrl: './multi-selection.component.html',
  styleUrls: ['./multi-selection.component.scss']
})
export class MultiSelectionComponent {

  @ViewChild('multiSelectionTable', { read: TableComponent, static: false }) multiSelectionTable!: TableComponent;

  multiSelectionTableSettings = {
    dataSource: new window.Smart.DataAdapter({
      dataSource: this.dataService.generateData(50),
      dataFields: [
        'id: number',
        'firstName: string',
        'lastName: string',
        'productName: string',
        'quantity: number',
        'price: number',
        'total: number'
      ]
    }),
    onInit: () => {

      this.multiSelectionTable.sortBy('lastName', 'asc');
      this.multiSelectionTable.select([3, 5, 11]);
      
    },
    paging: true,
    selection: true,
    sortMode: 'one',
    tooltip: true,
    columns: [
      { label: 'id', dataField: 'id', dataType: 'number' },
      { label: 'First Name', dataField: 'firstName', dataType: 'string', responsivePriority: 4 },
      { label: 'Last Name', dataField: 'lastName', dataType: 'string' },
      { label: 'Product Name', dataField: 'productName', dataType: 'string' },
      { label: 'Quantity', dataField: 'quantity', dataType: 'number', responsivePriority: 3 },
      { label: 'Price', dataField: 'price', dataType: 'number', responsivePriority: 3 },
      { label: 'Total', dataField: 'total', dataType: 'number' }
    ]
  }

  constructor(private dataService: DataService) { }

}

<div class="container multi-selection">
    <div class="custom-row">
        <div class="multi-selection-header custom-col">
            <h4>Table With Multi Selection</h4>
        </div>
    </div>

    <div class="custom-card">
        <div class="card-body">
            <smart-table #multiSelectionTable id="multi-selection" [dataSource]="multiSelectionTableSettings.dataSource"
                [paging]="multiSelectionTableSettings.paging" [sortMode]="multiSelectionTableSettings.sortMode"
                [tooltip]="multiSelectionTableSettings.tooltip" [onInit]="multiSelectionTableSettings.onInit"
                [columns]="multiSelectionTableSettings.columns" [selection]="multiSelectionTableSettings.selection">
            </smart-table>
        </div>
    </div>
</div>

// templates/admin-template-react/src/Pages/DataTables/MultiSelection/MultiSelection.js
import { useEffect } from 'react';

import withAnimation from '../../../hoc/withAnimation';

import { Table } from '../../../smartImports';

import { defaultTitle } from '../../../contexts/themeContext';

import { generateData } from '../../../services/dataService';

function MultiSelection() {

    useEffect(() => { document.title = `Multi Selection - ${defaultTitle}` }, []);

    const tableData = {
        dataSource: new window.Smart.DataAdapter({
            dataSource: generateData(50),
            dataFields: [
                'id: number',
                'firstName: string',
                'lastName: string',
                'productName: string',
                'quantity: number',
                'price: number',
                'total: number'
            ]
        }),
        onLoad() {
            this.sortBy('lastName', 'asc');
            this.select([3, 5, 11]);
        },
        paging: true,
        selection: true,
        sortMode: 'one',
        tooltip: true,
        columns: [
            { label: 'id', dataField: 'id', dataType: 'number' },
            { label: 'First Name', dataField: 'firstName', dataType: 'string', responsivePriority: 4 },
            { label: 'Last Name', dataField: 'lastName', dataType: 'string' },
            { label: 'Product Name', dataField: 'productName', dataType: 'string' },
            { label: 'Quantity', dataField: 'quantity', dataType: 'number', responsivePriority: 3 },
            { label: 'Price', dataField: 'price', dataType: 'number', responsivePriority: 3 },
            { label: 'Total', dataField: 'total', dataType: 'number' }
        ]
    }

    return (
        <div className="container">
            <div className="row">
                <div className="col-12 mb-3"><h4>Table With Multi Selection</h4></div>
            </div>

            <div className="card">
                <div className="card-body">
                    <Table
                        id="table"
                        {...tableData}
                    ></Table>
                </div>
            </div>
        </div>
    )
}

export default withAnimation(MultiSelection)
